"use strict";
const $=x=>document.getElementById(x),on=(x,e,f)=>{const n=$(x);if(n)n.addEventListener(e,f)};
const num=(id,d=0)=>{const n=$(id);return n?(parseFloat(n.value)||d):d},val=id=>{const n=$(id);return n?n.value:""};
const fmt=(x,n=2)=>Number(x).toFixed(n),ceil=Math.ceil,floor=Math.floor;

function svc(){if(!$('svc-pick'))return;const map={run:['行程抽象與 CPU 排程','第 01、02 章'],file:['檔案系統把位元組、名稱與磁碟區塊包成檔案','第 07、09 章'],net:['網路裝置驅動、中斷與系統呼叫共同工作','第 08、09 章'],crash:['使用者模式、位址空間與核心保護負責隔離故障','第 05、09 章'],mem:['虛擬記憶體以分頁配置、回收或換出記憶體','第 05、06 章']};const draw=()=>{const [service,chapter]=map[val('svc-pick')]||map.run;$('svc-output').innerHTML=`<strong>背後服務：${service}</strong><br>對應${chapter}。應用程式看到的是穩定介面；核心仍要仲裁真實硬體、記錄狀態並阻止越權。`};on('svc-pick','input',draw);draw()}
function memlayout(){if(!$('mem-code'))return;const draw=()=>{const parts=['mem-code','mem-data','mem-heap','mem-stack'].map(id=>Math.max(0,num(id))),total=parts.reduce((s,x)=>s+x,0),limit=1024;$('mem-output').innerHTML=`<strong>總用量 = ${parts.join(' + ')} = ${fmt(total,0)} KB</strong><br>低位址 → code ${parts[0]} KB → data ${parts[1]} KB → heap ${parts[2]} KB ↑ … 未用空間 … ↓ stack ${parts[3]} KB → 高位址<br>${total>limit?`總量超過示意上限 ${limit} KB，位址空間有被填滿的風險。`:`距示意上限 ${limit} KB 尚有 ${fmt(limit-total,0)} KB；heap 與 stack 仍會相向成長。`}`};['mem-code','mem-data','mem-heap','mem-stack'].forEach(id=>on(id,'input',draw));draw()}
function sched(){if(!$('sch-b1'))return;const draw=()=>{const b=['sch-b1','sch-b2','sch-b3'].map(id=>Math.max(1,floor(num(id,1)))),q=Math.max(1,floor(num('sch-q',1))),fc=[],fw=[],rem=[...b],done=[0,0,0],queue=[0,1,2];let t=0,slices=0;for(let i=0;i<3;i++){t+=b[i];fc[i]=t;fw[i]=fc[i]-b[i]}t=0;while(queue.length){const i=queue.shift(),run=Math.min(rem[i],q);rem[i]-=run;t+=run;slices++;if(rem[i]>0)queue.push(i);else done[i]=t}const rw=done.map((c,i)=>c-b[i]),avg=a=>a.reduce((s,x)=>s+x,0)/a.length,rows=(c,w)=>c.map((x,i)=>`P${i+1}: W=${w[i]} ms、T=${x} ms`).join('；');$('sch-output').innerHTML=`<strong>FCFS</strong><br>${rows(fc,fw)}<br>平均等待 ${fmt(avg(fw))} ms；平均周轉 ${fmt(avg(fc))} ms。<br><strong>RR（q=${q} ms，共 ${slices} 個執行片段）</strong><br>${rows(done,rw)}<br>平均等待 ${fmt(avg(rw))} ms；平均周轉 ${fmt(avg(done))} ms。<br>RR 讓工作輪流取得 CPU，通常對短工作較公平，但執行片段越多，可能發生的 context switch 也越多。`};['sch-b1','sch-b2','sch-b3','sch-q'].forEach(id=>on(id,'input',draw));draw()}
function amdahl(){if(!$('amd-p'))return;const draw=()=>{const p=Math.max(0,Math.min(1,num('amd-p'))),n=Math.max(1,floor(num('amd-n',1))),s=1/((1-p)+p/n),limit=p>=1?'無限大（教學模型假設全部可平行）':fmt(1/(1-p));$('amd-output').innerHTML=`<strong>加速比 S = 1 ÷ ((1−${fmt(p,2)}) + ${fmt(p,2)} ÷ ${n}) = ${fmt(s)} 倍</strong><br>N→∞ 時理論上限 = 1÷(1−p) = ${limit}。不能平行的比例仍要串行執行，所以核心增加的邊際收益會下降。`};['amd-p','amd-n'].forEach(id=>on(id,'input',draw));draw()}
function race(){if(!$('race-n'))return;const draw=()=>{const n=Math.max(1,floor(num('race-n',1))),lock=val('race-mode')==='lock',result=lock?2*n:n+1;$('race-output').innerHTML=`<strong>${lock?'有鎖':'無鎖最壞交錯'}：最終值 = ${result}</strong><br>${lock?`兩條執行緒各加 ${n} 次，臨界區一次只准一條進入，所以 2×${n}=${result}。`:`理想值是 2×${n}=${2*n}；最壞交錯只剩 ${n}+1=${result}。兩者讀到相同舊值後各自加一再寫回，後寫覆蓋先寫，形成更新遺失（lost update）。`}`};['race-n','race-mode'].forEach(id=>on(id,'input',draw));draw()}
function addr(){if(!$('va-addr'))return;const draw=()=>{const a=Math.max(0,floor(num('va-addr'))),size=Math.max(1,floor(num('va-pagesize',4096))),page=floor(a/size),offset=a%size;$('va-output').innerHTML=`<strong>頁號 = ⌊${a} ÷ ${size}⌋ = ${page}；頁內偏移 = ${a} mod ${size} = ${offset} byte</strong><br>驗算：${page} × ${size} + ${offset} = ${page*size} byte。頁表只需轉換頁號；偏移在頁內保持不變。`};['va-addr','va-pagesize'].forEach(id=>on(id,'input',draw));draw()}
function pager(){if(!$('pr-string'))return;const draw=()=>{const pages=(val('pr-string').match(/-?\d+/g)||[]).map(Number),capacity=Math.max(1,floor(num('pr-frames',1)));if(!pages.length){$('pr-output').innerHTML='<strong>請輸入至少一個整數頁號。</strong>';return}const fifo=()=>{const frames=[],order=[];let faults=0;for(const p of pages){if(frames.includes(p))continue;faults++;if(frames.length>=capacity){const victim=order.shift();frames.splice(frames.indexOf(victim),1)}frames.push(p);order.push(p)}return faults},lru=()=>{const frames=[],used=new Map();let faults=0,t=0;for(const p of pages){t++;if(!frames.includes(p)){faults++;if(frames.length>=capacity){let victim=frames[0];for(const f of frames)if(used.get(f)<used.get(victim))victim=f;frames.splice(frames.indexOf(victim),1)}frames.push(p)}used.set(p,t)}return faults},ff=fifo(),lf=lru();$('pr-output').innerHTML=`<strong>${pages.length} 次存取、${capacity} 個框架</strong><br>FIFO：page fault ${ff} 次，命中 ${pages.length-ff} 次。<br>LRU：page fault ${lf} 次，命中 ${pages.length-lf} 次。<br>FIFO 換掉最早進入者；LRU 換掉最久沒被存取者。兩者都由同一參考字串逐項模擬，結果不保證 LRU 每次都少。`};['pr-string','pr-frames'].forEach(id=>on(id,'input',draw));draw()}
function fsblock(){if(!$('fs-size'))return;const draw=()=>{const size=Math.max(0,num('fs-size')),block=Math.max(1,num('fs-block',4)),blocks=ceil(size/block),pointers=floor(block*1024/4),direct=blocks<=12;$('fs-output').innerHTML=`<strong>需要區塊數 = ⌈${fmt(size,2)} ÷ ${block}⌉ = ${blocks}</strong><br>${direct?`${blocks} ≤ 12，直接指標足夠，尚餘 ${12-blocks} 個。`:`${blocks} > 12，超出的 ${blocks-12} 塊需由間接指標描述。`}<br>一個 ${block} KB 間接指標區塊可放 ${block}×1024÷4 = ${pointers} 個 4-byte 指標${!direct&&blocks-12>pointers?'；本簡化模型的一層間接指標仍不夠。':'。'}`};['fs-size','fs-block'].forEach(id=>on(id,'input',draw));draw()}
function iocost(){if(!$('io-data'))return;const draw=()=>{const data=Math.max(0,num('io-data')),rate=Math.max(0.000001,num('io-rate',1)),irq=Math.max(0,num('io-irq')),chunk=Math.max(0.000001,num('io-chunk',1)),transfer=data/(rate*1024)*1000000,count=ceil(data/chunk),over=count*irq,ratio=transfer?over/transfer*100:0;$('io-output').innerHTML=`<strong>純傳輸時間 ≈ ${fmt(data,2)} ÷ (${fmt(rate,2)}×1024) = ${fmt(transfer,2)} μs</strong><br>中斷次數 ≈ ⌈${fmt(data,2)} ÷ ${fmt(chunk,2)}⌉ = ${count}；中斷總開銷 = ${count}×${fmt(irq,2)} = ${fmt(over,2)} μs。<br>中斷開銷相對純傳輸時間 = ${fmt(ratio)}%。chunk 越大，中斷通常越少，但資料湊成一塊後才處理的等待延遲可能更高。`};['io-data','io-rate','io-irq','io-chunk'].forEach(id=>on(id,'input',draw));draw()}
function syscall(){if(!$('sys-total'))return;const draw=()=>{const total=Math.max(0,num('sys-total')),chunk=Math.max(1,num('sys-chunk',1)),cost=Math.max(0,num('sys-cost')),count=ceil(total/chunk),over=count*cost;$('sys-output').innerHTML=`<strong>syscall 次數 = ⌈${fmt(total,2)} ÷ ${fmt(chunk,2)}⌉ = ${count}</strong><br>總固定成本 = ${count}×${fmt(cost,2)} = ${fmt(over,2)} μs。<br>若每次改搬 ${fmt(chunk*2,2)} KB，次數會成為 ${ceil(total/(chunk*2))}，固定成本約 ${fmt(ceil(total/(chunk*2))*cost,2)} μs。緩衝把許多小操作合併，減少跨越核心邊界的次數。`};['sys-total','sys-chunk','sys-cost'].forEach(id=>on(id,'input',draw));draw()}
function deadlock(){if(!$('dl-c1'))return;const names=['互斥','持有並等待','不可搶佔','循環等待'],ways=['讓資源可共享','一次要求全部資源，或等待前先釋放已持有資源','允許系統搶回並稍後重試','規定所有工作依同一資源順序取得'],ids=['dl-c1','dl-c2','dl-c3','dl-c4'];const draw=()=>{const states=ids.map(id=>val(id)==='on'),broken=states.map((x,i)=>x?-1:i).filter(i=>i>=0);$('dl-output').innerHTML=broken.length===0?'<strong>四條件同時成立：可能發生死結。</strong><br>「可能」不是「必然」；還要真的形成互等資源的循環。':'<strong>不會死結：至少一個必要條件被打破。</strong><br>'+broken.map(i=>`${names[i]}已關閉；實務手段：${ways[i]}。`).join('<br>')};ids.forEach(id=>on(id,'input',draw));draw()}
function dictionary(){const q=$('term-search');if(!q)return;const cards=[...document.querySelectorAll('.term-card')],draw=()=>{const s=q.value.trim().toLocaleLowerCase('zh-Hant');let n=0;cards.forEach(c=>{const hit=(c.textContent+' '+(c.dataset.search||'')).toLocaleLowerCase('zh-Hant').includes(s);c.hidden=!hit;if(hit)n++});$('term-count').textContent=`顯示 ${n} 個條目`};on('term-search','input',draw);draw()}
[svc,memlayout,sched,amdahl,race,addr,pager,fsblock,iocost,syscall,deadlock,dictionary].forEach(f=>f());
if(typeof module!=="undefined")module.exports={};
