(function(){"use strict";
var steps=["basics","i2c","spi","rs485","modbus","debug"],current=0,done={},timer=null,remaining=1800,key="engineerStudy.iotHardwareBus.v1";
var terms={
 physical:["接線／電氣層","真的銅線、腳位與電壓。先問有沒有供電、共地、接反或電壓不相容。","示波器上會看到高低電位、邊緣太慢、雜訊或完全沒訊號。"],
 transaction:["時序／交易層","規定誰先講、什麼時候讀一個位元，以及一次對話怎麼開始和結束。","邏輯分析儀會顯示 START、ACK、CS、clock 等事件。"],
 protocol:["封包／資料層","把位元組解釋成設備地址、命令、資料與錯誤碼。","線路可能完全正常，但站號或暫存器填錯仍會失敗。"],
 pushpull:["推挽（push-pull）","腳位裡可想成上下兩顆受控開關：送 1 時接向電源，送 0 時接向地，所以高低都由它主動驅動。","切換快；但兩個推挽輸出若一個推高、一個拉低，會形成電源到地的低阻抗路徑。"],
 opendrain:["開漏（open-drain）","只保留下方那顆接地開關：導通時把線拉成 0，關閉時與線脫離。它從來不主動送出 1。","很多裝置可以共線；任何一顆拉低，整條線就是 0。全部放手後才由上拉回到 1。"],
 pullup:["上拉電阻（pull-up）","把訊號線透過一顆電阻接到正電源。全部裝置放手時，它替線路電容充電，讓電壓逐漸回到 1。","電阻避免裝置拉低時把電源直接短路到地。太大會升得慢；太小則低電位時耗電較多。"],
 differential:["差動訊號（differential）","用兩條線的電壓差代表 0／1，而不是只看一條線對地多高。","兩條線一起沾到的雜訊較容易被抵消，適合 RS-485 長線。"],
 termination:["終端電阻（termination）","讓線尾負載等於電纜的特性阻抗。前進的波抵達時看不到阻抗突變，因此不必產生反向波來重新滿足電壓／電流關係。","匹配時訊號能量進入電阻並成為熱，反射係數為 0。它處理反射，不是一般的抗雜訊濾波器。"],
 ground:["共地／參考地（ground reference）","電壓永遠是兩點之間的差；設備仍需要彼此可接受的參考範圍。","RS-485 雖看差動，卻不是無限耐共模電壓。不同地電位很大時要考慮隔離。"]};
function q(s){return document.querySelector(s)}function qa(s){return Array.prototype.slice.call(document.querySelectorAll(s))}function say(t){q("#live-summary").textContent=t}
function save(){try{localStorage.setItem(key,JSON.stringify(done))}catch(e){}}
function load(){try{done=JSON.parse(localStorage.getItem(key)||"{}")||{}}catch(e){done={}}updateProgress()}
function complete(step){done[step]=true;save();updateProgress()}
function updateProgress(){var count=steps.filter(function(s){return done[s]}).length;q("#progress-text").textContent=count+" / 6";q("#progress-fill").style.width=(count/6*100)+"%";q(".progress").setAttribute("aria-valuenow",count);qa(".route-step").forEach(function(b){var d=!!done[b.dataset.step];b.classList.toggle("done",d);b.querySelector("em").textContent=d?"●":"○"})}
function show(index,focus){current=Math.max(0,Math.min(steps.length-1,index));qa(".lesson").forEach(function(p){p.classList.toggle("active",p.dataset.panel===steps[current])});qa(".route-step").forEach(function(b){b.classList.toggle("active",b.dataset.step===steps[current])});q("#step-position").textContent=(current+1)+" / 6";q("#prev-step").disabled=current===0;q("#next-step").textContent=current===5?"回到第一關 ↺":"下一關 →";location.hash=steps[current];if(focus){var h=q('[data-panel="'+steps[current]+'"] h2');h.focus()}window.scrollTo({top:0,behavior:"smooth"})}
qa(".route-step").forEach(function(b){b.addEventListener("click",function(){show(steps.indexOf(b.dataset.step),true)})});q("#prev-step").addEventListener("click",function(){show(current-1,true)});q("#next-step").addEventListener("click",function(){show(current===5?0:current+1,true)});
qa("[data-term]").forEach(function(b){b.addEventListener("click",function(){var t=terms[b.dataset.term];q("#term-title").textContent=t[0];q("#term-plain").textContent=t[1];q("#term-effect").textContent=t[2];say(t[0]+"："+t[1])})});
function renderPullup(state,track){var r=+q("#pull-r").value,current=3.3/r;q("#pull-r-out").textContent=r.toFixed(1)+" kΩ";if(state==="low"){q("#pull-voltage").textContent="接近 0 V（0）";q("#pull-current").textContent="約 "+current.toFixed(2)+" mA";q("#pull-explain").textContent="電晶體導通後形成 3.3 V → 電阻 → 電晶體 → GND 的完整路徑。電阻限制電流，同時線被拉到低電位。"}else{q("#pull-voltage").textContent="約 3.3 V（1）";q("#pull-current").textContent="約 0 mA";q("#pull-explain").textContent="電晶體關閉後，通往地的路徑斷開。上拉電阻替線路電容充電；充飽後兩端幾乎沒有壓差，所以穩態直流電流接近 0。"}if(track){say(q("#pull-explain").textContent);complete("basics")}}
q("#pull-r").addEventListener("input",function(){q("#pull-r-out").textContent=(+this.value).toFixed(1)+" kΩ"});qa("[data-pull-state]").forEach(function(b){b.addEventListener("click",function(){renderPullup(b.dataset.pullState,true)})});
function renderTermination(track){var z0=120,rl=+q("#term-r").value,g=(rl-z0)/(rl+z0),m=Math.abs(g);q("#term-r-out").textContent=rl+" Ω";q("#load-label").textContent="負載 "+rl+" Ω";q("#reflection-value").textContent=(g>=0?"+":"")+g.toFixed(2);q("#reflection-percent").textContent=Math.round(m*100)+"%";q("#reflection-arrow").style.opacity=Math.max(.05,m);q("#reflection-arrow").textContent=g<0?"← 反相反射":"← 同相反射";if(m<.03)q("#term-explain").textContent="負載與 120 Ω 電纜匹配。波抵達線尾時，電壓／電流比例仍連續，不必產生反射波；能量在電阻中轉成熱。";else if(g>0)q("#term-explain").textContent="負載比電纜阻抗大，線尾偏向開路；反射和原波同方向，可能讓電壓過衝。";else q("#term-explain").textContent="負載比電纜阻抗小，線尾偏向短路；反射會反相，可能造成下衝或多次過門檻。";if(track){say(q("#term-explain").textContent);complete("basics")}}
q("#term-r").addEventListener("input",function(){renderTermination(true)});
function i2cCalc(){var r=+q("#i2c-r").value,c=+q("#i2c-c").value,s=+q("#i2c-speed").value,tr=.8473*r*c,limit=s===100?1000:300;q("#i2c-r-out").textContent=r.toFixed(1)+" kΩ";q("#i2c-c-out").textContent=c+" pF";q("#i2c-rise").textContent=tr.toFixed(0)+" ns";q("#i2c-slope").style.width=Math.max(15,Math.min(95,tr/limit*65))+"%";var ok=tr<=limit;q("#i2c-result").textContent=ok?"估算在門檻內：線應能及時回到高電位；仍要在最差電壓、溫度與裝置數下量波形。":"上升太慢：接收器可能在取樣時還看不到 1。可減小上拉、縮短線、減少裝置或降低速度。";say(q("#i2c-result").textContent);complete("i2c")}
q("#i2c-r").addEventListener("input",i2cCalc);q("#i2c-c").addEventListener("input",i2cCalc);q("#i2c-speed").addEventListener("change",i2cCalc);q("#i2c-check").addEventListener("click",i2cCalc);
var faults={address:"很多資料表寫 7-bit 位址 0x48；0x90 可能是把位址先左移又重複加入讀寫位。先用邏輯分析儀看線上實際送出的地址。",power:"先量感測器 VCC 與 GND，再查上電後要等多久。沒上電的裝置不可能 ACK。",stuck:"某個裝置可能在傳到一半重置，仍抓住 SDA。先找誰拉低；常見復原是切換 SCL 數次，再送 STOP 或重置該裝置。"};qa("[data-i2c-fault]").forEach(function(b){b.addEventListener("click",function(){q("#i2c-fault-text").textContent=faults[b.dataset.i2cFault];say(faults[b.dataset.i2cFault])})});
qa("[data-spi-mode]").forEach(function(b){b.addEventListener("click",function(){var m=+b.dataset.spiMode,cpol=m>=2?1:0,cpha=m%2;q("#spi-verdict").textContent="Mode "+m+"：CPOL="+cpol+"、CPHA="+cpha;q("#spi-explain").textContent="時脈閒置為"+(cpol?"高":"低")+"，接收端在第"+(cpha?"二":"一")+"個有效邊緣取樣。只要晶片資料表和 MCU 設定一致就正確；不一致時常像位元整排錯位。";say(q("#spi-explain").textContent);complete("spi")})});
qa("[data-choice]").forEach(function(b){b.addEventListener("click",function(){q("#choice-result").textContent=b.dataset.choice==="i2c"?"選 I²C：兩條線可用位址掛多顆慢速裝置。":"選 SPI：多用幾支腳，換取薄封包與高吞吐；Flash 的命令、CS 時序仍看資料表。"})});
q("#rs-check").addEventListener("click",function(){var f=[],ok=true;if(q("#rs-topology").value!=="line"){f.push("星狀長支線容易形成多個反射點；改成一條主幹、支線盡量短。");ok=false}if(!q("#rs-term-a").checked||!q("#rs-term-b").checked||q("#rs-term-mid").checked){f.push("終端應在電纜物理兩端，不是每台設備都裝。");ok=false}if(!q("#rs-bias").checked)f.push("沒有人驅動時可能沒有確定狀態；確認收發器內建 failsafe，否則設計偏壓。 ");var de=q("#rs-de").value;if(de==="buffer"){f.push("軟體 buffer 空不等於線上送完；太早關 DE 會切掉最後位元。");ok=false}if(de==="late"){f.push("DE 放開太晚，遠端回應開頭可能撞上你的發送器。");ok=false}if(!f.length)f.push("基本拓樸通過。下一步仍要依電纜阻抗、長度、速率與收發器資料表量測。");q("#rs-verdict").textContent=ok?"基本接法合理":"找到會讓現場不穩的地方";q("#rs-findings").innerHTML=f.map(function(x){return"<li>"+x+"</li>"}).join("");say(q("#rs-verdict").textContent);complete("rs485")});
function crc16(bytes){var crc=0xffff;bytes.forEach(function(v){crc^=v;for(var i=0;i<8;i++)crc=(crc&1)?(crc>>>1)^0xA001:crc>>>1});return crc&0xffff}function hex(v){return v.toString(16).toUpperCase().padStart(2,"0")}
q("#mb-build").addEventListener("click",function(){var a=+q("#mb-address").value,doc=+q("#mb-register").value,n=+q("#mb-count").value,baud=+q("#mb-baud").value;if(a<1||a>247||doc<40001||doc>49999||n<1||n>125){q("#mb-meaning").textContent="輸入超出這個教學器的範圍。";return}var start=doc-40001,bytes=[a,3,start>>8,start&255,n>>8,n&255],crc=crc16(bytes),all=bytes.concat([crc&255,crc>>8]),gap=baud>19200?1.75:3.5*11/baud*1000;q("#mb-frame").innerHTML=all.map(function(v,i){return"<span title=\""+(["地址","功能 03","起點高位","起點低位","數量高位","數量低位","CRC 低位","CRC 高位"][i])+"\">"+hex(v)+"</span>"}).join("");q("#mb-crc").textContent="0x"+hex(crc>>8)+hex(crc&255);q("#mb-gap").textContent=gap.toFixed(2)+" ms";q("#mb-meaning").textContent="文件 "+doc+" → 封包起點 "+start+"（0x"+hex(start>>8)+hex(start&255)+"）。CRC 在 RTU 線上先放低位元組。"+(baud>19200?" 規格對高鮑率建議固定 t3.5 = 1.75 ms。":"");say("Modbus 封包已產生");complete("modbus")});
var mbErr={timeout:"先分層：站號／鮑率／parity、A/B 接反、DE、對方供電都可能讓它完全不回。先看線上有沒有請求與回應。",crc:"偶發 CRC 常指向雜訊、反射、終端或碰撞；若每次都同樣錯，再查 CRC 實作與 byte 順序。",exception:"這其實是有效回應：設備收到請求，但拒絕該功能或地址。先讀 exception code 與設備 register map。"};qa("[data-mb-error]").forEach(function(b){b.addEventListener("click",function(){q("#mb-error-text").textContent=mbErr[b.dataset.mbError];say(mbErr[b.dataset.mbError])})});
var debugGuide={physical:["第 1 層：先證明電氣正常","量供電與 A/B 差動波形，確認接線、拓樸、終端、反射、雜訊與地電位。短線正常、長線才壞，這層尤其優先。"],bytes:["第 2 層：把波形還原成位元組","用邏輯分析儀或 UART log 確認鮑率、資料格式、DE 切換與實際收發內容。先證明收到的 bytes 和送出的相同。"],frame:["第 3 層：解讀 Modbus","確認設備地址、功能碼、0-based register address、CRC 與 exception code。有效 exception 代表底下兩層多半已通。"],firmware:["第 4 層：最後查韌體狀態","檢查 ring buffer overflow、parser 狀態、timeout 起算點與重試策略。此時底層已有證據，不會把接線問題誤診為 parser bug。"]};qa("[data-debug]").forEach(function(b){b.addEventListener("click",function(){var g=debugGuide[b.dataset.debug];q("#debug-verdict").textContent=g[0];q("#debug-explain").textContent=g[1];say(g[1]);complete("debug")})});
q("#reset-all").addEventListener("click",function(){done={};save();updateProgress()});q("#timer-toggle").addEventListener("click",function(){if(timer){clearInterval(timer);timer=null;this.textContent="繼續倒數";return}this.textContent="暫停";timer=setInterval(function(){remaining=Math.max(0,remaining-1);q("#time-label").textContent=String(Math.floor(remaining/60)).padStart(2,"0")+":"+String(remaining%60).padStart(2,"0");if(!remaining){clearInterval(timer);timer=null;say("30 分鐘到，直接做最後的現場診斷。")}},1000)});
load();renderPullup("release",false);renderTermination(false);var hash=location.hash.slice(1);show(Math.max(0,steps.indexOf(hash)),false);
}());
