"use strict";
const $=x=>document.getElementById(x),on=(x,e,f)=>{const n=$(x);if(n)n.addEventListener(e,f)};
const rad=d=>d*Math.PI/180,deg=r=>r*180/Math.PI,clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),fmt=(x,n=3)=>Number(x).toFixed(n);
const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),norm=a=>Math.hypot(...a),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const mv=(A,v)=>A.map(r=>dot(r,v)),vec=(v,n=3)=>`(${v.map(x=>fmt(x,n)).join(", ")})`;
const rot3=(axis,a)=>{const c=Math.cos(a),s=Math.sin(a);return axis==="x"?[[1,0,0],[0,c,-s],[0,s,c]]:axis==="y"?[[c,0,s],[0,1,0],[-s,0,c]]:[[c,-s,0],[s,c,0],[0,0,1]]};

function taskmath(){if(!$('task-pick'))return;const map={pose:['第 02、03 章：座標與向量','運動學的末端位姿'],rotate:['第 05、09 章：二維與三維旋轉','運動學的姿態與座標鏈'],path:['第 08、10、11 章：變換、方程式與梯度','路徑規劃的座標轉換與最佳化'],see:['第 02、06、07、08、12 章','機器人視覺的像素、法線、相機外參與雜訊'],learn:['第 06、11、12 章：內積、梯度與機率','機器人學習的相似度、更新方向與期望回報']};const draw=()=>{const [math,course]=map[$('task-pick').value];$('taskmath-output').innerHTML=`<strong>這個任務需要的數學＝${math}</strong><br>對應到${course}。因為任務必須先把位置、方向或不確定性變成可計算的數，演算法才能做決定。`};on('task-pick','input',draw);draw()}
function trig(){if(!$('angle-deg'))return;const draw=()=>{const d=+$('angle-deg').value,a=rad(d),c=Math.cos(a),s=Math.sin(a),t=Math.abs(c)<1e-10?'未定義（cosθ≈0，不能除以零）':fmt(s/c);$('trig-output').innerHTML=`<strong>θ=${fmt(d,0)}° = ${fmt(a,4)} rad</strong><br>(cosθ, sinθ)=${vec([c,s])}<br>cos²θ+sin²θ=${fmt(c*c+s*s)}（≈1，因為點仍在半徑 1 的單位圓上，所以旋轉不改變長度。）<br>tanθ=${t}`};on('angle-deg','input',draw);draw()}
function point(){if(!$('pt-x'))return;const draw=()=>{const x=+$('pt-x').value,y=+$('pt-y').value,d=Math.hypot(x,y),a=d===0?null:deg(Math.atan2(y,x));let q=x===0&&y===0?'原點':x===0||y===0?'座標軸上':x>0&&y>0?'第一象限':x<0&&y>0?'第二象限':x<0&&y<0?'第三象限':'第四象限';$('point-output').innerHTML=`<strong>點 ${vec([x,y],1)} 位於${q}，距原點 ${fmt(d)}</strong><br>方向角=${a===null?'未定義（原點沒有方向）':fmt(a,1)+'°'}。距離來自畢氏定理 √(x²+y²)；atan2 同時讀 x、y 的正負，所以能分辨象限。`};['pt-x','pt-y'].forEach(x=>on(x,'input',draw));draw()}
function vector(){if(!$('ax'))return;const draw=()=>{const a=[+$('ax').value,+$('ay').value],b=[+$('bx').value,+$('by').value],k=+$('k').value,n=norm(a),u=n<1e-12?'未定義（零向量沒有方向）':vec(a.map(x=>x/n));$('vector-output').innerHTML=`<strong>|a|=${fmt(n)}，a 的單位向量=${u}</strong><br>a+b=${vec(a.map((x,i)=>x+b[i]))}：把兩段位移首尾接起來。<br>k·a=${vec(a.map(x=>k*x))}：${k<0?'長度縮放並反向':k===0?'縮成零向量':'方向不變，只縮放長度'}。`};['ax','ay','bx','by','k'].forEach(x=>on(x,'input',draw));draw()}
function matvec(){if(!$('m-a'))return;const draw=()=>{const a=+$('m-a').value,b=+$('m-b').value,c=+$('m-c').value,d=+$('m-d').value,v=[+$('v-x').value,+$('v-y').value],r=[a*v[0]+b*v[1],c*v[0]+d*v[1]];let why=a===1&&b===0&&c===0&&d===1?'這是單位矩陣，每列只取回原分量，所以點沒動。':b!==0||c!==0?'非對角項會把一個軸的分量混進另一軸，產生剪切、反射或旋轉效果。':'對角項分別縮放 x、y 分量。';$('matvec-output').innerHTML=`<strong>M·v=${vec(r)}</strong><br>第一列：${fmt(a,1)}×${fmt(v[0],1)}+${fmt(b,1)}×${fmt(v[1],1)}=${fmt(r[0])}；第二列同理得到 ${fmt(r[1])}。${why}`};['m-a','m-b','m-c','m-d','v-x','v-y'].forEach(x=>on(x,'input',draw));draw()}
function rot2d(){if(!$('rot-angle'))return;const draw=()=>{const a=rad(+$('rot-angle').value),x=+$('rot-x').value,y=+$('rot-y').value,c=Math.cos(a),s=Math.sin(a),r=[x*c-y*s,x*s+y*c];$('rot2d-output').innerHTML=`<strong>旋轉後=${vec(r)}</strong><br>轉前長度=${fmt(Math.hypot(x,y))}，轉後長度=${fmt(norm(r))}。兩者相同，因為旋轉矩陣只改方向；它的 sin、cos 滿足 cos²θ+sin²θ=1。`};['rot-angle','rot-x','rot-y'].forEach(x=>on(x,'input',draw));draw()}
function dotWidget(){if(!$('dax'))return;const draw=()=>{const a=[+$('dax').value,+$('day').value],b=[+$('dbx').value,+$('dby').value],d=dot(a,b),na=norm(a),nb=norm(b),valid=na*nb>1e-12,ang=valid?deg(Math.acos(clamp(d/(na*nb),-1,1))):null,proj=nb>1e-12?d/nb:null,kind=Math.abs(d)<1e-10?'=0，兩方向垂直':d>0?'>0，夾角小於 90°，大致同向':'<0，夾角大於 90°，大致反向';$('dot-output').innerHTML=`<strong>a·b=${fmt(d)}（${kind}）</strong><br>夾角=${ang===null?'未定義（至少一個是零向量）':fmt(ang,1)+'°'}；a 在 b 上的帶正負投影長=${proj===null?'未定義':fmt(proj)}。內積用 cosφ 衡量兩方向對齊程度。`};['dax','day','dbx','dby'].forEach(x=>on(x,'input',draw));draw()}
function crossWidget(){if(!$('cax'))return;const draw=()=>{const a=[+$('cax').value,+$('cay').value,+$('caz').value],b=[+$('cbx').value,+$('cby').value,+$('cbz').value],c=cross(a,b);$('cross-output').innerHTML=`<strong>a×b=${vec(c)}，|a×b|=${fmt(norm(c))}</strong><br>這個長度等於兩向量撐出的平行四邊形面積。驗證：(a×b)·a=${fmt(dot(c,a))}，(a×b)·b=${fmt(dot(c,b))}，都約為 0，所以結果同時垂直於 a、b；若面積為 0，兩向量平行或有零向量。`};['cax','cay','caz','cbx','cby','cbz'].forEach(x=>on(x,'input',draw));draw()}
function compose(){if(!$('cmp-angle'))return;const draw=()=>{const a=rad(+$('cmp-angle').value),t=[+$('cmp-tx').value,+$('cmp-ty').value],p=[+$('cmp-px').value,+$('cmp-py').value],c=Math.cos(a),s=Math.sin(a),R=v=>[c*v[0]-s*v[1],s*v[0]+c*v[1]],rt=R(p).map((x,i)=>x+t[i]),tr=R(p.map((x,i)=>x+t[i])),same=norm(rt.map((x,i)=>x-tr[i]))<1e-10;$('compose-output').innerHTML=`<strong>先旋轉後平移：${vec(rt)}</strong><br>先平移後旋轉：${vec(tr)}<br>${same?'這組特殊參數得到相同終點。':'終點不同，因為第二種順序連平移向量也一起旋轉；矩陣乘法一般不可交換。'}`};['cmp-angle','cmp-tx','cmp-ty','cmp-px','cmp-py'].forEach(x=>on(x,'input',draw));draw()}
function rot3d(){if(!$('r3-axis1'))return;const draw=()=>{const a1=$('r3-axis1').value,a2=$('r3-axis2').value,R1=rot3(a1,rad(+$('r3-a1').value)),R2=rot3(a2,rad(+$('r3-a2').value)),p=[+$('r3-px').value,+$('r3-py').value,+$('r3-pz').value],p12=mv(R2,mv(R1,p)),p21=mv(R1,mv(R2,p)),same=norm(p12.map((x,i)=>x-p21[i]))<1e-10;$('rot3d-output').innerHTML=`<strong>先 ${a1.toUpperCase()} 後 ${a2.toUpperCase()}：${vec(p12)}</strong><br>先 ${a2.toUpperCase()} 後 ${a1.toUpperCase()}：${vec(p21)}<br>${same?'目前的軸、角度或點形成特殊情況，結果相同。':'結果不同：第一次旋轉已改變點相對第二根軸的位置，所以三維旋轉一般不可交換。'}`};['r3-axis1','r3-a1','r3-axis2','r3-a2','r3-px','r3-py','r3-pz'].forEach(x=>on(x,'input',draw));draw()}
function solve2(){if(!$('s-a'))return;const draw=()=>{const a=+$('s-a').value,b=+$('s-b').value,c=+$('s-c').value,d=+$('s-d').value,e=+$('s-e').value,f=+$('s-f').value,det=a*d-b*c;if(Math.abs(det)<1e-10){$('solve2-output').innerHTML=`<strong>det=${fmt(det)}，奇異：兩直線平行或重合，無唯一解。</strong><br>行列式為零代表兩列提供相同方向的限制；可能互相矛盾而無解，也可能重複同一條線而有無限多解。`;return}const x=(e*d-b*f)/det,y=(a*f-e*c)/det;$('solve2-output').innerHTML=`<strong>det=${fmt(det)}，唯一解 (x,y)=${vec([x,y])}</strong><br>代回第一式得 ${fmt(a*x+b*y)}=${fmt(e)}，第二式得 ${fmt(c*x+d*y)}=${fmt(f)}。det≠0 表示兩條直線方向不同，只交於一點。`};['s-a','s-b','s-c','s-d','s-e','s-f'].forEach(x=>on(x,'input',draw));draw()}
function deriv(){if(!$('fn-pick'))return;const draw=()=>{const kind=$('fn-pick').value,x=+$('fn-x').value,h=1e-3,f=t=>kind==='sq'?t*t:Math.sin(t),numeric=(f(x+h)-f(x-h))/(2*h),exact=kind==='sq'?2*x:Math.cos(x),g=[2*x,2],down=[-2*x,-2];$('deriv-output').innerHTML=`<strong>${kind==='sq'?'f(x)=x²':'f(x)=sin x'} 在 x=${fmt(x,1)}：中央差斜率=${fmt(numeric,5)}，解析斜率=${fmt(exact,5)}</strong><br>中央差比較左右各 h 的輸出，估計輸入每增加 1 時輸出如何變。另對 F(x,y)=x²+y²，在 (${fmt(x,1)},1) 的梯度=${vec(g,1)}，指向上升最快；負梯度=${vec(down,1)}，因此沿它走會靠近原點、讓 F 下降。`};['fn-pick','fn-x'].forEach(x=>on(x,'input',draw));draw()}
function noise(){if(!$('noise-true'))return;const draw=()=>{const truth=+$('noise-true').value,s=+$('noise-sigma').value,N=+$('noise-N').value,b=+$('noise-bias').value,u=s/Math.sqrt(N);$('noise-output').innerHTML=`<strong>真值=${fmt(truth,1)}；平均讀值的中心約 ${fmt(truth+b,2)}；標準不確定度 σ/√N=${fmt(u,3)}</strong><br>單次 σ=${fmt(s,1)}，平均 ${N} 次只把獨立隨機雜訊縮成 ${fmt(u,3)}；系統偏差 ${fmt(b,1)} 不隨 N 改變，所以再多量測也不會自動回到真值。`};['noise-true','noise-sigma','noise-N','noise-bias'].forEach(x=>on(x,'input',draw));draw()}
function dictionary(){const q=$('term-search');if(!q)return;const cards=[...document.querySelectorAll('.term-card')],draw=()=>{const s=q.value.trim().toLocaleLowerCase('zh-Hant');let n=0;cards.forEach(c=>{const hit=(c.textContent+' '+(c.dataset.search||'')).toLocaleLowerCase('zh-Hant').includes(s);c.hidden=!hit;if(hit)n++});$('term-count').textContent=`顯示 ${n} 個條目`};on('term-search','input',draw);draw()}
[taskmath,trig,point,vector,matvec,rot2d,dotWidget,crossWidget,compose,rot3d,solve2,deriv,noise,dictionary].forEach(f=>f());
if(typeof module!=="undefined")module.exports={rad,deg,clamp,dot,norm,cross,mv,rot3};
