"use strict";
const $=id=>document.getElementById(id),on=(id,e,f)=>{const n=$(id);if(n)n.addEventListener(e,f)},num=id=>Number($(id)?.value),fmt=(x,d=3)=>Number(x).toFixed(d);
function split(){if(!$("split-scenes"))return;const draw=()=>{const scenes=num("split-scenes"),random=$("split-mode").value==="random",leak=random&&scenes<20;const msg=leak?"高洩漏風險：相鄰 frame 可能分散到訓練與測試。":"較能測量跨場景泛化，但仍要檢查操作者、物件與環境是否重複。";$("split-output").innerHTML=`<strong>${msg}</strong><br>共有 ${scenes} 個獨立場景；機器人資料應優先按 episode、場景或時間區段切分，不以高度相似的單幀隨機切分冒充泛化。`};["split-scenes","split-mode"].forEach(x=>on(x,"input",draw));draw()}
function bc(){if(!$("bc-error"))return;const draw=()=>{const e=num("bc-error"),T=num("bc-horizon"),p=1-Math.pow(1-e,T);$("bc-output").innerHTML=`<strong>若每步錯誤獨立，至少一次錯誤的示意機率為 ${fmt(100*p,1)}%。</strong><br>1−(1−e)<sup>T</sup>只建立誤差累積直覺；真實錯誤會改變後續觀測分布，常比獨立模型更糟。`};["bc-error","bc-horizon"].forEach(x=>on(x,"input",draw));draw()}
function returns(){if(!$("ret-gamma"))return;const draw=()=>{const gamma=num("ret-gamma"),rewards=$("ret-seq").value.split(",").map(Number).filter(Number.isFinite);let G=0,p=1;rewards.forEach(r=>{G+=p*r;p*=gamma});$("ret-output").innerHTML=`<strong>折扣回報 G=${fmt(G,3)}。</strong><br>γ=${fmt(gamma,2)}；較小 γ 更重視近期獎勵。獎勵是設計的訓練訊號，不一定等於真正任務價值。`};["ret-gamma","ret-seq"].forEach(x=>on(x,"input",draw));draw()}
function explore(){if(!$("exp-rate"))return;const draw=()=>{const e=num("exp-rate"),unsafe=num("exp-unsafe"),episodes=num("exp-episodes"),risky=e*unsafe*episodes;const msg=risky<1?"示意風險暴露低，但仍非零":risky<10?"需要安全層與模擬先行":"不可直接用於無保護實機探索";$("exp-output").innerHTML=`<strong>預期危險探索事件指標約 ${fmt(risky,1)}：${msg}。</strong><br>指標=探索率×危險動作比例×episode 數；它不是機率保證，只提醒探索成本不能從演算法公式中消失。`};["exp-rate","exp-unsafe","exp-episodes"].forEach(x=>on(x,"input",draw));draw()}
function sim(){if(!$("sim-range"))return;const draw=()=>{const range=num("sim-range"),real=num("sim-real"),inside=Math.abs(real)<=range;const width=2*range,why=inside?"真實值落在訓練範圍，但組合分布與動態仍可能失配。":"真實值落在訓練支撐之外，策略正在外插。";$("sim-output").innerHTML=`<strong>${inside?"有覆蓋":"未覆蓋"}；隨機化寬度 ${fmt(width,2)}。</strong><br>${why} 範圍越寬不一定越好：模型容量與資料有限時，過寬會稀釋有效練習。`};["sim-range","sim-real"].forEach(x=>on(x,"input",draw));draw()}
function gate(){if(!$("gate-baseline"))return;const draw=()=>{const b=$("gate-baseline").value==="yes",ood=$("gate-ood").value==="yes",stop=$("gate-stop").value==="yes",shadow=$("gate-shadow").value==="yes";let title,why;if(!b){title="不可部署";why="沒有非學習基線，無法判斷模型是否真的改善。"}else if(!ood){title="不可擴大場景";why="尚未測試分布外與失敗案例。"}else if(!stop){title="不可接管致動";why="沒有獨立安全限制與停止路徑。"}else if(!shadow){title="先做 shadow mode";why="讓策略只輸出建議，與現行控制並行比對。"}else{title="可進低風險分階段試驗";why="仍須限制速度、工作區與回退條件，並持續監測。"}$("gate-output").innerHTML=`<strong>${title}</strong><br>${why}`};["gate-baseline","gate-ood","gate-stop","gate-shadow"].forEach(x=>on(x,"input",draw));draw()}
function dictionary(){const q=$("term-search");if(!q)return;const cards=[...document.querySelectorAll(".term-card")],draw=()=>{const s=q.value.trim().toLocaleLowerCase("zh-Hant");let c=0;cards.forEach(x=>{const hit=x.textContent.toLocaleLowerCase("zh-Hant").includes(s);x.hidden=!hit;if(hit)c++});$("term-count").textContent=`顯示 ${c} 個條目`};on("term-search","input",draw);draw()}
[split,bc,returns,explore,sim,gate,dictionary].forEach(f=>f());
