"use strict";
const $=id=>document.getElementById(id), on=(id,event,fn)=>{const e=$(id);if(e)e.addEventListener(event,fn)}, n=id=>Number($(id)?.value), f=(x,d=3)=>Number(x).toFixed(d);
function clearance(){if(!$("clear-distance"))return;const draw=()=>{const c=n("clear-distance")-n("clear-radius")-n("clear-margin");let msg=c>0?`仍有 ${f(c)} m 模型間隙。`:c===0?"恰好落在安全邊界；浮點誤差與模型誤差仍可能使它不安全。":`侵入安全邊界 ${f(-c)} m。`;$("clear-output").innerHTML=`<strong>${msg}</strong><br>計算是障礙距離 − 碰撞半徑 − 額外餘裕。它只驗證目前這個離散狀態，不能證明兩個狀態之間的連續運動無碰撞。`};["clear-distance","clear-radius","clear-margin"].forEach(x=>on(x,"input",draw));draw()}
function astar(){if(!$("astar-weight"))return;const draw=()=>{const w=n("astar-weight"),blocked=n("astar-blocked"),base=20+blocked*5,expanded=Math.max(5,Math.round(base/(.35+w))),guarantee=w<=1?"若 h 從不高估，仍保有最短路徑保證。":"加權後可能更快，但已放棄一般的最短路徑保證。";$("astar-output").innerHTML=`<strong>示意展開約 ${expanded} 個節點。</strong><br>f(n)=g(n)+${f(w,1)}h(n)。${guarantee} 此數字是教學指標，不是特定地圖的實測效能。`};["astar-weight","astar-blocked"].forEach(x=>on(x,"input",draw));draw()}
function sampling(){if(!$("sample-count"))return;const draw=()=>{const N=n("sample-count"),p=n("sample-hit"),P=1-Math.pow(1-p,N);$("sample-output").innerHTML=`<strong>至少一次命中狹窄通道的示意機率：${f(P*100,1)}%</strong><br>P=1−(1−p)<sup>N</sup>。增加樣本提高機會，但單次沒有命中不能證明無路；真實樣本也不是獨立同分布時，這個公式只供直覺。`};["sample-count","sample-hit"].forEach(x=>on(x,"input",draw));draw()}
function timing(){if(!$("time-dq"))return;const draw=()=>{const dq=n("time-dq"),v=n("time-v"),a=n("time-a"),tv=dq/v,ta=2*Math.sqrt(dq/a),T=Math.max(tv,ta);$("time-output").innerHTML=`<strong>單關節理想時間下界約 ${f(T,2)} s。</strong><br>速度下界 ${f(tv,2)} s，加速度對稱三角速度下界 ${f(ta,2)} s，取較大者。多關節還須同步；jerk、力矩、負載與控制週期會讓可執行時間更長。`};["time-dq","time-v","time-a"].forEach(x=>on(x,"input",draw));draw()}
function pipeline(){if(!$("pipe-collision"))return;const draw=()=>{const c=$("pipe-collision").value==="yes",limits=$("pipe-limits").value==="yes",dynamic=$("pipe-dynamic").value==="yes";let title,why;if(!c){title="不能交付路徑";why="沒有連續碰撞檢查，只驗證端點不夠。"}else if(!limits){title="幾何路徑不等於可執行軌跡";why="尚未套用速度、加速度與關節限制。"}else if(dynamic){title="需要監測與重規劃";why="環境會變，離線有效的軌跡可能在執行時失效。"}else{title="可進入受控執行驗證";why="仍須在模擬、低速實機與安全監控下分階段驗證。"}$("pipe-output").innerHTML=`<strong>${title}</strong><br>${why}`};["pipe-collision","pipe-limits","pipe-dynamic"].forEach(x=>on(x,"input",draw));draw()}
function constraintProjection(){if(!$("constraint-residual"))return;const draw=()=>{const initial=n("constraint-residual"),gain=n("constraint-gain"),steps=n("constraint-steps"),residual=initial*Math.pow(1-gain,steps),stable=gain<2,passed=Math.abs(residual)<=.5;const state=!stable?"步長超出這個線性模型的穩定範圍":passed?"已進入 ±0.5° 示意容許帶":"仍需迭代或改善局部模型";$("constraint-output").innerHTML=`<strong>${steps} 步後殘差約 ${f(residual,3)}°：${state}。</strong><br>示意更新為 rₖ₊₁=(1−α)rₖ。真實投影的 Jacobian 會隨 q 改變，收斂後仍須重新檢查碰撞、關節極限與整條邊。`};["constraint-residual","constraint-gain","constraint-steps"].forEach(x=>on(x,"input",draw));draw()}
function stoppingEnvelope(){if(!$("dyn-speed"))return;const draw=()=>{const v=n("dyn-speed"),a=n("dyn-decel"),tau=n("dyn-latency")/1000,clear=n("dyn-clearance"),delay=v*tau,brake=v*v/(2*a),stop=delay+brake,margin=clear-stop;$("dyn-output").innerHTML=`<strong>理想停止包絡 ${f(stop,3)} m；目前${margin>=0?`尚餘 ${f(margin,3)} m`:`短缺 ${f(-margin,3)} m`}。</strong><br>延遲距離 ${f(delay,3)} m + 制動距離 ${f(brake,3)} m。這尚未加入定位誤差、障礙移動、jerk、負載與控制追蹤誤差，不能當作認證安全距離。`};["dyn-speed","dyn-decel","dyn-latency","dyn-clearance"].forEach(x=>on(x,"input",draw));draw()}
function dictionary(){const q=$("term-search");if(!q)return;const cards=[...document.querySelectorAll(".term-card")],draw=()=>{const s=q.value.trim().toLocaleLowerCase("zh-Hant");let count=0;cards.forEach(c=>{const hit=c.textContent.toLocaleLowerCase("zh-Hant").includes(s);c.hidden=!hit;if(hit)count++});$("term-count").textContent=`顯示 ${count} 個條目`};on("term-search","input",draw);draw()}
[clearance,astar,sampling,timing,pipeline,constraintProjection,stoppingEnvelope,dictionary].forEach(fn=>fn());
