"use strict";
const $=id=>document.getElementById(id), on=(id,event,fn)=>{const e=$(id);if(e)e.addEventListener(event,fn)}, n=id=>Number($(id)?.value), f=(x,d=3)=>Number(x).toFixed(d);
function clearance(){if(!$("clear-distance"))return;const draw=()=>{const c=n("clear-distance")-n("clear-radius")-n("clear-margin");let msg=c>0?`仍有 ${f(c)} m 模型間隙。`:c===0?"恰好落在安全邊界；浮點誤差與模型誤差仍可能使它不安全。":`侵入安全邊界 ${f(-c)} m。`;$("clear-output").innerHTML=`<strong>${msg}</strong><br>計算是障礙距離 − 碰撞半徑 − 額外餘裕。它只驗證目前這個離散狀態，不能證明兩個狀態之間的連續運動無碰撞。`};["clear-distance","clear-radius","clear-margin"].forEach(x=>on(x,"input",draw));draw()}
function astar(){if(!$("astar-weight"))return;const draw=()=>{const w=n("astar-weight"),blocked=n("astar-blocked"),base=20+blocked*5,expanded=Math.max(5,Math.round(base/(.35+w))),guarantee=w<=1?"若 h 從不高估，仍保有最短路徑保證。":"加權後可能更快，但已放棄一般的最短路徑保證。";$("astar-output").innerHTML=`<strong>示意展開約 ${expanded} 個節點。</strong><br>f(n)=g(n)+${f(w,1)}h(n)。${guarantee} 此數字是教學指標，不是特定地圖的實測效能。`};["astar-weight","astar-blocked"].forEach(x=>on(x,"input",draw));draw()}
function sampling(){if(!$("sample-count"))return;const draw=()=>{const N=n("sample-count"),p=n("sample-hit"),P=1-Math.pow(1-p,N);$("sample-output").innerHTML=`<strong>至少一次命中狹窄通道的示意機率：${f(P*100,1)}%</strong><br>P=1−(1−p)<sup>N</sup>。增加樣本提高機會，但單次沒有命中不能證明無路；真實樣本也不是獨立同分布時，這個公式只供直覺。`};["sample-count","sample-hit"].forEach(x=>on(x,"input",draw));draw()}
function timing(){if(!$("time-dq"))return;const draw=()=>{const dq=n("time-dq"),v=n("time-v"),a=n("time-a"),tv=dq/v,ta=2*Math.sqrt(dq/a),T=Math.max(tv,ta);$("time-output").innerHTML=`<strong>單關節理想時間下界約 ${f(T,2)} s。</strong><br>速度下界 ${f(tv,2)} s，加速度對稱三角速度下界 ${f(ta,2)} s，取較大者。多關節還須同步；jerk、力矩、負載與控制週期會讓可執行時間更長。`};["time-dq","time-v","time-a"].forEach(x=>on(x,"input",draw));draw()}
function pipeline(){if(!$("pipe-collision"))return;const draw=()=>{const c=$("pipe-collision").value==="yes",limits=$("pipe-limits").value==="yes",dynamic=$("pipe-dynamic").value==="yes";let title,why;if(!c){title="不能交付路徑";why="沒有連續碰撞檢查，只驗證端點不夠。"}else if(!limits){title="幾何路徑不等於可執行軌跡";why="尚未套用速度、加速度與關節限制。"}else if(dynamic){title="需要監測與重規劃";why="環境會變，離線有效的軌跡可能在執行時失效。"}else{title="可進入受控執行驗證";why="仍須在模擬、低速實機與安全監控下分階段驗證。"}$("pipe-output").innerHTML=`<strong>${title}</strong><br>${why}`};["pipe-collision","pipe-limits","pipe-dynamic"].forEach(x=>on(x,"input",draw));draw()}
function dictionary(){const q=$("term-search");if(!q)return;const cards=[...document.querySelectorAll(".term-card")],draw=()=>{const s=q.value.trim().toLocaleLowerCase("zh-Hant");let count=0;cards.forEach(c=>{const hit=c.textContent.toLocaleLowerCase("zh-Hant").includes(s);c.hidden=!hit;if(hit)count++});$("term-count").textContent=`顯示 ${count} 個條目`};on("term-search","input",draw);draw()}
[clearance,astar,sampling,timing,pipeline,dictionary].forEach(fn=>fn());
