"use strict";
const id=x=>document.getElementById(x);const on=(x,e,f)=>{const n=id(x);if(n)n.addEventListener(e,f)};const num=x=>Number(id(x)?.value||0);

function bits(){if(!id("bit-next"))return;const states=["時脈邊緣前：輸入可改變，暫存器仍保留舊值","有效時脈邊緣：暫存器取樣輸入","邊緣後：輸出成為新狀態，組合邏輯開始重新計算","穩定後：下一個狀態輸入已準備好，等待下個邊緣"];let step=0;const draw=()=>{id("bit-output").innerHTML=`<strong>步驟 ${step+1}/4</strong><br>${states[step]}`};on("bit-next","click",()=>{step=(step+1)%4;draw()});on("bit-reset","click",()=>{step=0;draw()});draw()}
function endian(){if(!id("endian-value"))return;const draw=()=>{const raw=id("endian-value").value.trim();const v=/^0x[0-9a-f]+$/i.test(raw)?Number.parseInt(raw.slice(2),16):Number(raw);if(!Number.isInteger(v)||v<0||v>0xFFFFFFFF){id("endian-output").textContent="請輸入 0 到 4294967295 的十進位整數，或 0x00000000 到 0xFFFFFFFF。";return}const hex=v.toString(16).toUpperCase().padStart(8,"0");const bytes=hex.match(/../g);const little=[...bytes].reverse();id("endian-output").innerHTML=`<strong>32 位元值：${v.toLocaleString("zh-Hant")} （0x${hex}）</strong><br>大端序低位址到高位址：${bytes.join(" ")}<br>小端序低位址到高位址：${little.join(" ")}<br>位元組序改變多位元組值的記憶體排列，不改變單一位元組內的位元順序。`};on("endian-value","input",draw);draw()}
function cycle(){if(!id("cycle-stage"))return;const data=["程式計數器提供指令位址，指令記憶體回傳機器指令","控制單元解碼操作與欄位，暫存器檔讀出來源值","算術邏輯單元運算、比較或形成有效位址","載入／儲存指令讀寫資料記憶體；其他指令可略過","結果在時脈邊緣寫回目的暫存器，成為後續指令狀態"];const draw=()=>{const n=num("cycle-stage");id("cycle-output").innerHTML=`<strong>${["取指","解碼／讀暫存器","執行","記憶體存取","寫回"][n]}</strong><br>${data[n]}<br>這五段是因果模型；真實微架構可拆更多級、重疊、亂序或融合。`};on("cycle-stage","input",draw);draw()}
function isa(){if(!id("isa-next"))return;const program=["載入立即值 3 到 R0","載入立即值 4 到 R1","R0 ← R0 + R1","比較 R0 與 7","若相等，跳到結束"];let pc=0,r0=0,r1=0,z=false;const draw=()=>{const ended=pc>=program.length;id("isa-next").disabled=ended;id("isa-output").innerHTML=`<strong>${ended?"程式結束；":`\u7a0b\u5f0f\u8a08\u6578\u5668=${pc}\uff0c`}R0=${r0}，R1=${r1}，零旗標=${z?1:0}</strong><pre>${program.map((x,i)=>(i===pc?"> ":"  ")+i+" "+x).join("\n")}</pre>組合語言只是機器指令的助記表示；處理器實際解碼位元欄位。`};on("isa-next","click",()=>{if(pc===0)r0=3;else if(pc===1)r1=4;else if(pc===2)r0+=r1;else if(pc===3)z=r0===7;else if(pc===4&&z){pc=program.length;draw();return}pc=Math.min(pc+1,program.length);draw()});on("isa-reset","click",()=>{pc=0;r0=0;r1=0;z=false;draw()});draw()}
function memory(){if(!id("memory-level"))return;const latency={register:[1,"暫存器直接供執行單元使用"],cache:[4,"快取以區塊保存近期資料"],ram:[120,"主記憶體需經記憶體控制器"],page:[1000000,"缺頁需作業系統載入頁面，示意代價極大"]};const checkbox=id("translation-hit"),control=id("translation-control");let rememberedHit=checkbox.checked;const draw=()=>{const level=id("memory-level").value,[n,why]=latency[level];control.hidden=level==="register";checkbox.disabled=level==="register"||level==="page";if(level==="page")checkbox.checked=false;else checkbox.checked=rememberedHit;let translation="";if(level==="page")translation="轉譯失誤，且頁表標示頁面未駐留，因此交給作業系統處理。";else if(level!=="register")translation=checkbox.checked?"位址轉譯快取命中，可直接取得實體頁框。":"轉譯快取失誤，硬體需走頁表；這不等於資料頁一定缺頁。";id("memory-output").innerHTML=`<strong>示意延遲：${n.toLocaleString()} 個相對週期</strong><br>${why}。${translation}<br>這是邏輯依賴與量級模型；真實處理器可平行進行部分轉譯與快取查找。`};on("memory-level","change",draw);on("translation-hit","input",()=>{rememberedHit=checkbox.checked;draw()});draw()}
function abi(){if(!id("abi-args"))return;const draw=()=>{const args=num("abi-args"),locals=num("abi-locals"),reg=Math.min(args,4),stack=Math.max(args-4,0);const raw=16+locals,frame=Math.ceil(raw/16)*16,padding=frame-raw;id("abi-output").innerHTML=`<strong>${reg} 個參數走示意參數暫存器，${stack} 個由呼叫端在其框架內準備；被呼叫端框架約 ${frame} 位元組。</strong><br>被呼叫端模型含 16 位元組保存資訊、${locals} 位元組區域資料與 ${padding} 位元組對齊填補。真實暫存器數、保存責任、名稱修飾與例外展開由平台應用程式二進位介面決定。`};on("abi-args","input",draw);on("abi-locals","input",draw);draw()}
function compile(){if(!id("compile-stage"))return;const data={pre:["前處理後原始碼","展開引入檔、巨集與條件編譯；仍是語言文字"],front:["語意中介表示","剖析語法、型別檢查並建立較抽象的中介表示"],opt:["最佳化中介表示","可內聯、刪除無用程式、常數傳播或重排；原始結構可能消失"],back:["組合語言／機器指令選擇","依目標指令集、暫存器與呼叫慣例降低成目標相關操作"],asm:["可重定位目的檔","組譯器編碼指令，建立區段、符號與尚待連結的重定位；整合式組譯器可讓文字組合檔不必落地"]};const draw=()=>{const [title,why]=data[id("compile-stage").value];id("compile-output").innerHTML=`<strong>${title}</strong><br>${why}<br>${id("compile-opt").checked?"啟用最佳化：原始函式邊界、變數位置與執行順序可能更難一對一對回。":"關閉最佳化：通常較易除錯，但仍不是原始碼的逐行翻譯。"}`};on("compile-stage","change",draw);on("compile-opt","input",draw);draw()}
function link(){if(!id("link-symbol"))return;const draw=()=>{const symbol=id("link-symbol").value,provider=id("link-provider").value;let result;if(provider==="none")result="未定義符號沒有提供者：連結失敗";else if(provider==="two")result="出現多個強定義：通常衝突，需依語言與連結規則處理";else result=`符號 ${symbol} 解析到一個提供者；連結器可套用相關重定位`;const output=id("link-output"),title=document.createElement("strong");title.textContent=result;output.replaceChildren(title,document.createElement("br"),document.createTextNode("重定位記錄指出「哪個位置」要依「哪個符號或區段」在最終布局確定後修正。靜態連結把所需內容納入成品；動態連結保留執行期共享與解析責任。"))};on("link-symbol","input",draw);on("link-provider","change",draw);draw()}
function loader(){if(!id("load-base"))return;const draw=()=>{const base=num("load-base"),offset=num("load-offset"),lazy=id("lazy-binding").checked;id("loader-output").innerHTML=`<strong>示意虛擬位址：0x${(base+offset).toString(16).toUpperCase()}</strong><br>映像基底 + 區段相對位移。此合併模型包含：作業系統建立初始映射、動態連結器載入共享函式庫與解析符號、語言執行期及配置器再按需管理堆積。${lazy?"延遲綁定：外部函式第一次呼叫時才完成目標解析。":"立即綁定：啟動時先解析需要的外部函式。"}`};on("load-base","change",draw);on("load-offset","input",draw);on("lazy-binding","input",draw);draw()}
function trace(){if(!id("trace-fault"))return;const data={compile:["編譯／最佳化","查看診斷、中介表示、編譯選項與產生的組合語言"],link:["符號解析／重定位","查看目的檔符號表、重定位、函式庫順序與連結器診斷"],load:["載入／動態連結","查看執行檔格式、相依函式庫、搜尋路徑、映射與載入器錯誤"],run:["指令／記憶體／系統呼叫","查看崩潰位址、暫存器、頁面權限、呼叫堆疊與作業系統事件"]};const draw=()=>{const [where,evidence]=data[id("trace-fault").value];id("trace-output").innerHTML=`<strong>先定位：${where}</strong><br>下一份證據：${evidence}。不要用後段症狀倒推前段一定出錯；例如「程式啟動失敗」可能是連結期漏符號，也可能是載入期找不到共享函式庫。`};on("trace-fault","change",draw);draw()}
function dictionary(){const q=id("term-search");if(!q)return;const cards=[...document.querySelectorAll(".term-card")],count=id("term-count");const draw=()=>{const s=q.value.trim().toLocaleLowerCase("zh-Hant");let n=0;cards.forEach(c=>{const hit=c.textContent.toLocaleLowerCase("zh-Hant").includes(s);c.hidden=!hit;if(hit)n++});count.textContent=`顯示 ${n} 個條目`};on("term-search","input",draw);draw()}
const quizData={
"00":[["六個反相器都收到低準位，共有幾個輸出為高？",6,0,"每個反相器都把低準位轉成高準位。"],["八個 NAND 中有三個的兩輸入皆為 1，共有幾個輸出為 0？",3,0,"NAND 只有在兩輸入皆為 1 時輸出 0。"],["充電需 2 ns、放電需 3 ns，一個來回至少幾 ns？",2+3,0,"一個來回包含充電與放電。"]],
"01":[["兩輸入 XOR 的四種輸入中，有幾組輸出為 1？",2,0,"01 與 10 共兩組。"],["六位元 MUX 的 A=45、B=18、S=1，輸出是多少？",18,0,"S=1 選 B。"],["DEMUX 的 IN=1、S=0；以十位表 Y0、個位表 Y1，答案是多少？",10,0,"S=0 時 Y0Y1=10。"]],
"02":[["四位元無號加法 6+9 的結果是多少？",(6+9)&15,0,"6+9=15。"],["全加器 A=1、B=0、Cin=1；把 CoutSum 當二進位讀成十進位是多少？",2,0,"總和為二進位 10。"],["四位元 13+6 溢出後，低四位的十進位值是多少？",(13+6)&15,0,"19 的低四位是 0011。"]],
"03":[["D 正反器依序取樣 0、1、0，最後 Q 是多少？",0,0,"最後一次取樣覆寫 Q。"],["八位元暫存器保存幾個位元？",8,0,"寬度就是保存的位元數。"],["6×8 位元記憶體共保存幾個位元？",6*8,0,"6×8=48。"]],
"04":[["四位元組指令模型中，PC=0x2000 的循序下一址換成十進位是多少？",0x2000+4,0,"0x2004 是 8196。"],["ADD 的來源值為 9 與 6，寫回值是多少？",9+6,0,"9+6=15。"],["LOAD 的基底 0x3000、位移 12，有效位址換成十進位是多少？",0x3000+12,0,"12288+12=12300。"]],
"05":[["把 9 寫入 EAX 後，RAX 的十進位值是多少？",9,0,"寫 EAX 會清除 RAX 高 32 位。"],["位址為 0x2000+3×4+8，換成十進位是多少？",0x2000+3*4+8,0,"結果為 8212。"],["有號比較 -2<3 成立填 1，否則填 0。",Number(-2<3),0,"條件成立。"]],
"06":[["把 9 寫入 W3 後，X3 的十進位值是多少？",9,0,"寫 W3 會清除高 32 位。"],["基底 0x1000、索引 2、元素 8 位元組，有效位址換成十進位是多少？",0x1000+2*8,0,"結果為 4112。"],["SUBS 計算 12−12 後，Z 是多少？",Number(12-12===0),0,"結果為零，Z=1。"]],
"07":[["slli 將 5 左移 3 位，結果是多少？",5<<3,0,"左移 3 位等於乘 8。"],["addi a0,x0,9 後，a0 是多少？",9,0,"x0 永遠讀出 0。"],["四位元組指令位於 0x3000，jal 的返回位址換成十進位是多少？",0x3000+4,0,"0x3004 是 12292。"]],
"08":[["0xA1B2C3D4 以小端序存放，最低位址位元組換成十進位是多少？",0xD4,0,"D4 是 212。"],["4 KiB 頁面下，0x12ABC 的頁內位移換成十進位是多少？",0xABC,0,"低 12 位是 2748。"],["4 KiB 頁面下，0x23456 的頁號換成十進位是多少？",Math.floor(0x23456/4096),0,"頁號 0x23 是 35。"]],
"09":[["保存資訊 16 加區域資料 40，向上對齊 16 後共幾位元組？",Math.ceil((16+40)/16)*16,0,"56 對齊為 64。"],["四個參數暫存器遇到七個參數，幾個走堆疊？",7-4,0,"其餘 3 個走堆疊。"],["保存資訊 16、區域資料 34，對齊至 16 需填補幾位元組？",64-(16+34),0,"50 對齊為 64，填補 14。"]],
"10":[["三個獨立 .cpp 各自前處理後，共有幾個翻譯單元？",3,0,"每個原始檔形成一個。"],["六條固定四位元組指令共占幾位元組？",6*4,0,"6×4=24。"],["區段起點 0x80 加位移 0x24，換成十進位是多少？",0x80+0x24,0,"0xA4 是 164。"]],
"11":[["S=0x5100、P=0x5004，S−P 換成十進位是多少？",0x5100-0x5004,0,"0xFC 是 252。"],["引用找到一個相容強定義，可建立幾個唯一綁定？",1,0,"恰好一個。"],["引用找不到供應者時，成功解析數是多少？",0,0,"沒有定義便無法解析。"]],
"12":[["基底 0x600000 加位移 0x3000，位址換成十進位是多少？",0x600000+0x3000,0,"0x603000 是 6303744。"],["0x80456 減基底 0x80000，位移換成十進位是多少？",0x80456-0x80000,0,"0x456 是 1110。"],["延遲綁定最早在第幾次呼叫觸發解析？",1,0,"第一次呼叫觸發。"]],
"13":[["PC=0x7F301ABC 減基底 0x7F300000，位移換成十進位是多少？",0x7F301ABC-0x7F300000,0,"0x1ABC 是 6844。"],["從 [RDI+8] 載入且 RDI=0，故障位址是多少？",8,0,"0+8=8。"],["原始證據再加一種交叉證據，總共至少幾種？",2,0,"至少兩種。"]]
};
function quizzes(){document.querySelectorAll("[data-quiz-chapter]").forEach(s=>{const c=s.dataset.quizChapter,h=s.querySelector(".quiz-items"),items=quizData[c]||[];if(!h)return;let saved={};try{saved=JSON.parse(localStorage.getItem("computer-org-quiz-"+c)||"{}")||{}}catch(_){saved={}}items.forEach((q,i)=>{const card=document.createElement("article"),p=document.createElement("p"),label=document.createElement("label"),input=document.createElement("input"),button=document.createElement("button"),feedback=document.createElement("p"),details=document.createElement("details"),summary=document.createElement("summary"),explanation=document.createElement("p");card.className="quiz-question";p.textContent=(i+1)+". "+q[0];label.textContent="你的答案";input.type="number";input.step="any";input.setAttribute("aria-label","第 "+(i+1)+" 題答案");button.type="button";button.textContent="檢查答案";feedback.className="quiz-feedback";feedback.setAttribute("aria-live","polite");summary.textContent="查看解析";explanation.textContent="答案："+q[1]+"；容差：±"+q[2]+"。"+q[3];details.append(summary,explanation);label.append(input);card.append(p,label,button,feedback,details);h.append(card);if(saved[i]){card.classList.add("is-correct");feedback.textContent="上次已答對，可重新作答。"}button.addEventListener("click",()=>{const v=Number(input.value),ok=input.value.trim()!==""&&Number.isFinite(v)&&Math.abs(v-q[1])<=q[2];card.classList.toggle("is-correct",ok);card.classList.toggle("is-wrong",!ok);feedback.textContent=ok?"答對了。":"尚未答對；容差為 ±"+q[2]+"。";if(ok){saved[i]=true;try{localStorage.setItem("computer-org-quiz-"+c,JSON.stringify(saved))}catch(_){}}})})})}
if(typeof document!=="undefined")[bits,endian,cycle,isa,memory,abi,compile,link,loader,trace,dictionary,quizzes].forEach(f=>f());
if(typeof module!=="undefined")module.exports={quizData};
