"use strict";
const id=x=>document.getElementById(x);const on=(x,e,f)=>{const n=id(x);if(n)n.addEventListener(e,f)};const num=x=>Number(id(x)?.value||0);

function bits(){if(!id("bit-next"))return;const states=["時脈邊緣前：輸入可改變，暫存器仍保留舊值","有效時脈邊緣：暫存器取樣輸入","邊緣後：輸出成為新狀態，組合邏輯開始重新計算","穩定後：下一個狀態輸入已準備好，等待下個邊緣"];let step=0;const draw=()=>{id("bit-output").innerHTML=`<strong>步驟 ${step+1}/4</strong><br>${states[step]}<br>8 個位元組成 1 個位元組；十六進位一位可表示 4 個位元。`};on("bit-next","click",()=>{step=(step+1)%4;draw()});on("bit-reset","click",()=>{step=0;draw()});draw()}
function endian(){if(!id("endian-value"))return;const draw=()=>{const v=num("endian-value")>>>0;const hex=v.toString(16).toUpperCase().padStart(8,"0");const bytes=hex.match(/../g);const little=[...bytes].reverse();id("endian-output").innerHTML=`<strong>32 位元值：0x${hex}</strong><br>大端序低位址到高位址：${bytes.join(" ")}<br>小端序低位址到高位址：${little.join(" ")}<br>位元組序改變多位元組值的記憶體排列，不改變單一位元組內的位元順序。`};on("endian-value","input",draw);draw()}
function cycle(){if(!id("cycle-stage"))return;const data=["程式計數器提供指令位址，指令記憶體回傳機器指令","控制單元解碼操作與欄位，暫存器檔讀出來源值","算術邏輯單元運算、比較或形成有效位址","載入／儲存指令讀寫資料記憶體；其他指令可略過","結果在時脈邊緣寫回目的暫存器，成為後續指令狀態"];const draw=()=>{const n=num("cycle-stage");id("cycle-output").innerHTML=`<strong>${["取指","解碼／讀暫存器","執行","記憶體存取","寫回"][n]}</strong><br>${data[n]}<br>這五段是因果模型；真實微架構可拆更多級、重疊、亂序或融合。`};on("cycle-stage","input",draw);draw()}
function isa(){if(!id("isa-next"))return;const program=["載入立即值 3 到 R0","載入立即值 4 到 R1","R0 ← R0 + R1","比較 R0 與 7","若相等，跳到結束"];let pc=0,r0=0,r1=0,z=false;const draw=()=>{id("isa-output").innerHTML=`<strong>程式計數器=${pc}，R0=${r0}，R1=${r1}，零旗標=${z?1:0}</strong><pre>${program.map((x,i)=>(i===pc?"> ":"  ")+i+" "+x).join("\n")}</pre>組合語言只是機器指令的助記表示；處理器實際解碼位元欄位。`};on("isa-next","click",()=>{if(pc===0)r0=3;else if(pc===1)r1=4;else if(pc===2)r0+=r1;else if(pc===3)z=r0===7;else if(pc===4&&z){pc=program.length;draw();return}pc=Math.min(pc+1,program.length);draw()});on("isa-reset","click",()=>{pc=0;r0=0;r1=0;z=false;draw()});draw()}
function memory(){if(!id("memory-level"))return;const latency={register:[1,"暫存器直接供執行單元使用"],cache:[4,"快取以區塊保存近期資料"],ram:[120,"主記憶體需經記憶體控制器"],page:[1000000,"缺頁需作業系統載入頁面，示意代價極大"]};const draw=()=>{const [n,why]=latency[id("memory-level").value];const translated=id("translation-hit").checked;id("memory-output").innerHTML=`<strong>示意延遲：${n.toLocaleString()} 個相對週期</strong><br>${why}。${translated?"位址轉譯快取命中，可直接取得實體頁框。":"轉譯快取失誤，硬體或作業系統需走頁表；這不等於資料頁一定缺頁。"}<br>這是邏輯依賴與量級模型；真實處理器可平行進行部分轉譯與快取查找。`};on("memory-level","change",draw);on("translation-hit","input",draw);draw()}
function abi(){if(!id("abi-args"))return;const draw=()=>{const args=num("abi-args"),locals=num("abi-locals"),reg=Math.min(args,4),stack=Math.max(args-4,0);const raw=16+stack*8+locals,frame=Math.ceil(raw/16)*16;id("abi-output").innerHTML=`<strong>${reg} 個參數走示意參數暫存器，${stack} 個走堆疊；框架約 ${frame} 位元組。</strong><br>模型另含 16 位元組保存資訊與 ${locals} 位元組區域資料，再對齊到 16。真實暫存器數、保存責任、名稱修飾與例外展開由平台應用程式二進位介面決定。`};on("abi-args","input",draw);on("abi-locals","input",draw);draw()}
function compile(){if(!id("compile-stage"))return;const data={pre:["前處理後原始碼","展開引入檔、巨集與條件編譯；仍是語言文字"],front:["語意中介表示","剖析語法、型別檢查並建立較抽象的中介表示"],opt:["最佳化中介表示","可內聯、刪除無用程式、常數傳播或重排；原始結構可能消失"],back:["組合語言／機器指令選擇","依目標指令集、暫存器與呼叫慣例降低成目標相關操作"],asm:["可重定位目的檔","組譯器編碼指令，建立區段、符號與尚待連結的重定位；整合式組譯器可讓文字組合檔不必落地"]};const draw=()=>{const [title,why]=data[id("compile-stage").value];id("compile-output").innerHTML=`<strong>${title}</strong><br>${why}<br>${id("compile-opt").checked?"啟用最佳化：原始函式邊界、變數位置與執行順序可能更難一對一對回。":"關閉最佳化：通常較易除錯，但仍不是原始碼的逐行翻譯。"}`};on("compile-stage","change",draw);on("compile-opt","input",draw);draw()}
function link(){if(!id("link-symbol"))return;const draw=()=>{const symbol=id("link-symbol").value,provider=id("link-provider").value;let result;if(provider==="none")result="未定義符號沒有提供者：連結失敗";else if(provider==="two")result="出現多個強定義：通常衝突，需依語言與連結規則處理";else result=`符號 ${symbol} 解析到一個提供者；連結器可套用相關重定位`;id("link-output").innerHTML=`<strong>${result}</strong><br>重定位記錄指出「哪個位置」要依「哪個符號或區段」在最終布局確定後修正。靜態連結把所需內容納入成品；動態連結保留執行期共享與解析責任。`};on("link-symbol","input",draw);on("link-provider","change",draw);draw()}
function loader(){if(!id("load-base"))return;const draw=()=>{const base=num("load-base"),offset=num("load-offset"),lazy=id("lazy-binding").checked;id("loader-output").innerHTML=`<strong>示意虛擬位址：0x${(base+offset).toString(16).toUpperCase()}</strong><br>映像基底 + 區段相對位移。此合併模型包含：作業系統建立初始映射、動態連結器載入共享函式庫與解析符號、語言執行期及配置器再按需管理堆積。${lazy?"延遲綁定：外部函式第一次呼叫時才完成目標解析。":"立即綁定：啟動時先解析需要的外部函式。"}`};on("load-base","change",draw);on("load-offset","input",draw);on("lazy-binding","input",draw);draw()}
function trace(){if(!id("trace-fault"))return;const data={compile:["編譯／最佳化","查看診斷、中介表示、編譯選項與產生的組合語言"],link:["符號解析／重定位","查看目的檔符號表、重定位、函式庫順序與連結器診斷"],load:["載入／動態連結","查看執行檔格式、相依函式庫、搜尋路徑、映射與載入器錯誤"],run:["指令／記憶體／系統呼叫","查看崩潰位址、暫存器、頁面權限、呼叫堆疊與作業系統事件"]};const draw=()=>{const [where,evidence]=data[id("trace-fault").value];id("trace-output").innerHTML=`<strong>先定位：${where}</strong><br>下一份證據：${evidence}。不要用後段症狀倒推前段一定出錯；例如「程式啟動失敗」可能是連結期漏符號，也可能是載入期找不到共享函式庫。`};on("trace-fault","change",draw);draw()}
function dictionary(){const q=id("term-search");if(!q)return;const cards=[...document.querySelectorAll(".term-card")],count=id("term-count");const draw=()=>{const s=q.value.trim().toLocaleLowerCase("zh-Hant");let n=0;cards.forEach(c=>{const hit=c.textContent.toLocaleLowerCase("zh-Hant").includes(s);c.hidden=!hit;if(hit)n++});count.textContent=`顯示 ${n} 個條目`};on("term-search","input",draw);draw()}
[bits,endian,cycle,isa,memory,abi,compile,link,loader,trace,dictionary].forEach(f=>f());
