"use strict";
const $=x=>document.getElementById(x), on=(x,e,f)=>{const n=$(x);if(n)n.addEventListener(e,f)}, rad=d=>d*Math.PI/180, deg=r=>r*180/Math.PI, clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const I=n=>Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j?1:0));
const mm=(A,B)=>A.map(r=>B[0].map((_,j)=>r.reduce((s,v,k)=>s+v*B[k][j],0)));
const mv=(A,v)=>A.map(r=>r.reduce((s,x,i)=>s+x*v[i],0));
const tr=A=>A[0].map((_,j)=>A.map(r=>r[j]));
const add=(a,b)=>a.map((x,i)=>x+b[i]), sub=(a,b)=>a.map((x,i)=>x-b[i]), scale=(a,s)=>a.map(x=>x*s), dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0), norm=a=>Math.hypot(...a), cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const Tmul=(A,B)=>mm(A,B), Tx=x=>[[1,0,0,x],[0,1,0,0],[0,0,1,0],[0,0,0,1]], Tz=z=>[[1,0,0,0],[0,1,0,0],[0,0,1,z],[0,0,0,1]];
const Rot=(axis,a)=>{const c=Math.cos(a),s=Math.sin(a),R=axis==="x"?[[1,0,0],[0,c,-s],[0,s,c]]:axis==="y"?[[c,0,s],[0,1,0],[-s,0,c]]:[[c,-s,0],[s,c,0],[0,0,1]];return [[...R[0],0],[...R[1],0],[...R[2],0],[0,0,0,1]]};
const pos=T=>[T[0][3],T[1][3],T[2][3]], Rof=T=>T.slice(0,3).map(r=>r.slice(0,3)), fmt=(x,n=3)=>Number(x).toFixed(n), vec=v=>`[${v.map(x=>fmt(x)).join(", ")}]`;
const axes=["z","y","x","y","x","y","x"];
function fk(q,details=false){let T=Tz(.20), origins=[],worldAxes=[];for(let i=0;i<7;i++){const R=Rof(T),u=axes[i]==="x"?[1,0,0]:axes[i]==="y"?[0,1,0]:[0,0,1];origins.push(pos(T));worldAxes.push(mv(R,u));T=Tmul(T,Rot(axes[i],q[i]));if(i===2)T=Tmul(T,Tx(.32));if(i===3)T=Tmul(T,Tx(.28));if(i===5)T=Tmul(T,Tx(.12))}return details?{T,origins,worldAxes}:T}
function jac(q){const d=fk(q,true),p=pos(d.T),J=Array.from({length:6},()=>Array(7).fill(0));for(let i=0;i<7;i++){const v=cross(d.worldAxes[i],sub(p,d.origins[i]));for(let r=0;r<3;r++){J[r][i]=v[r];J[r+3][i]=d.worldAxes[i][r]}}return J}
function solve(A,b){A=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<A.length;i++){let p=i;for(let r=i+1;r<A.length;r++)if(Math.abs(A[r][i])>Math.abs(A[p][i]))p=r;[A[i],A[p]]=[A[p],A[i]];if(Math.abs(A[i][i])<1e-12)return null;const d=A[i][i];for(let j=i;j<=A.length;j++)A[i][j]/=d;for(let r=0;r<A.length;r++)if(r!==i){const f=A[r][i];for(let j=i;j<=A.length;j++)A[r][j]-=f*A[i][j]}}return A.map(r=>r[A.length])}
function dls(J,e,l=.08){const JT=tr(J),A=mm(J,JT);for(let i=0;i<6;i++)A[i][i]+=l*l;const y=solve(A,e);return y?mv(JT,y):Array(7).fill(0)}
function det(A){A=A.map(r=>[...r]);let d=1;for(let i=0;i<A.length;i++){let p=i;for(let r=i+1;r<A.length;r++)if(Math.abs(A[r][i])>Math.abs(A[p][i]))p=r;if(Math.abs(A[p][i])<1e-12)return 0;if(p!==i){[A[i],A[p]]=[A[p],A[i]];d*=-1}d*=A[i][i];for(let r=i+1;r<A.length;r++){const f=A[r][i]/A[i][i];for(let j=i;j<A.length;j++)A[r][j]-=f*A[i][j]}}return d}
function frame(){if(!$('frame-angle'))return;const draw=()=>{const a=rad(+$('frame-angle').value),x=+$('frame-x').value,y=+$('frame-y').value,c=Math.cos(a),s=Math.sin(a);$('frame-output').innerHTML=`<strong>同一自由向量在旋轉座標系中的分量：${vec([c*x+s*y,-s*x+c*y],2)}</strong><br>這是被動換座標：幾何箭頭沒有轉，只是基底轉了。若主動旋轉箭頭，矩陣符號方向相反。`};['frame-angle','frame-x','frame-y'].forEach(x=>on(x,'input',draw));draw()}
function angleBasics(){if(!$('angle-deg'))return;const draw=()=>{const d=+$('angle-deg').value,a=rad(d);$('angle-output').innerHTML=`<strong>${fmt(d,0)}° = ${fmt(a,4)} rad</strong><br>長度 1 的箭頭方向分量為 [cosθ, sinθ] = [${fmt(Math.cos(a),3)}, ${fmt(Math.sin(a),3)}]。平方和約 ${fmt(Math.cos(a)**2+Math.sin(a)**2,3)}，所以旋轉沒有改變箭頭長度。`};on('angle-deg','input',draw);draw()}
function planar(){if(!$('arm-q1'))return;const draw=()=>{const a=rad(+$('arm-q1').value),b=rad(+$('arm-q2').value),l1=.6,l2=.4,x=l1*Math.cos(a)+l2*Math.cos(a+b),y=l1*Math.sin(a)+l2*Math.sin(a+b);$('arm-output').innerHTML=`<strong>末端位置 = ${vec([x,y])} m</strong><br>第二段的絕對方向是 q₁+q₂，不是 q₂。距離基座 ${fmt(Math.hypot(x,y))} m；可達範圍為 0.2–1.0 m。`};['arm-q1','arm-q2'].forEach(x=>on(x,'input',draw));draw()}
function ik2(){if(!$('ik2-x'))return;const draw=()=>{const x=+$('ik2-x').value,y=+$('ik2-y').value,l1=.6,l2=.4,c=(x*x+y*y-l1*l1-l2*l2)/(2*l1*l2);if(Math.abs(c)>1){$('ik2-output').innerHTML='<strong>不可達。</strong><br>目標距離超出兩連桿的環形工作空間；數值法再努力也不能改變幾何。';return}const b=Math.acos(clamp(c,-1,1)),sol=[b,-b].map(q2=>[Math.atan2(y,x)-Math.atan2(l2*Math.sin(q2),l1+l2*Math.cos(q2)),q2]);$('ik2-output').innerHTML=`<strong>兩組解：</strong><br>${sol.map((q,i)=>`肘${i?'下':'上'}：q₁=${fmt(deg(q[0]),1)}°，q₂=${fmt(deg(q[1]),1)}°`).join('<br>')}<br>逆運動學不是函式反解的單一答案；還要選分支。`};['ik2-x','ik2-y'].forEach(x=>on(x,'input',draw));draw()}
function rotation(){if(!$('rot-a'))return;const draw=()=>{const a=rad(+$('rot-a').value),b=rad(+$('rot-b').value),p=[1,0,0,1],R1=Tmul(Rot('z',a),Rot('y',b)),R2=Tmul(Rot('y',b),Rot('z',a));$('rot-output').innerHTML=`<strong>先 Z 後 Y：${vec(mv(R1,p).slice(0,3))}</strong><br>先 Y 後 Z：${vec(mv(R2,p).slice(0,3))}<br>三維旋轉通常不可交換；寫出矩陣作用在哪一側與旋轉所依座標系。`};['rot-a','rot-b'].forEach(x=>on(x,'input',draw));draw()}
function transform(){if(!$('tf-parent'))return;const draw=()=>{const a=rad(+$('tf-parent').value),b=rad(+$('tf-child').value),A=Tmul(Rot('z',a),Tx(.5)),B=Tmul(Rot('z',b),Tx(.3)),C=Tmul(A,B);$('tf-output').innerHTML=`<strong>末端原點（基座座標）=${vec(pos(C))}</strong><br><code>⁰T₂ = ⁰T₁ · ¹T₂</code>。右邊的局部變換先作用；交換乘法會描述另一條幾何鏈。`};['tf-parent','tf-child'].forEach(x=>on(x,'input',draw));draw()}
function qValues(){return Array.from({length:7},(_,i)=>rad(+($(`q${i+1}`)?.value||0)))}
function seven(){if(!$('q1'))return;const draw=()=>{const q=qValues(),T=fk(q),R=Rof(T);$('seven-output').innerHTML=`<strong>末端位置=${vec(pos(T))} m</strong><br>工具 x 軸=${vec(R.map(r=>r[0]))}<br>工具 z 軸=${vec(R.map(r=>r[2]))}<br>位置只是位姿的一半；兩組關節角可到同一點但工具方向不同。`};for(let i=1;i<=7;i++)on(`q${i}`,'input',draw);on('q-reset','click',()=>{for(let i=1;i<=7;i++)$(`q${i}`).value=0;draw()});draw()}
function jacobian(){if(!$('jac-joint'))return;const draw=()=>{const q=[0,.35,-.2,.7,.1,-.4,.2],J=jac(q),i=+$('jac-joint').value,lin=J.slice(0,3).map(r=>r[i]),ang=J.slice(3).map(r=>r[i]);$('jac-output').innerHTML=`<strong>第 ${i+1} 欄</strong><br>末端線速度貢獻=${vec(lin)} m/s（當該關節為 1 rad/s）<br>角速度貢獻=${vec(ang)} rad/s<br>旋轉關節公式：線速度欄 = 軸向量 ×（末端位置 − 關節原點）。`};on('jac-joint','input',draw);draw()}
function nullspace(){if(!$('null-pref'))return;const draw=()=>{const q=[0,.35,-.2,.7,.1,-.4,.2],J=jac(q),v=[0,0,+$('null-pref').value,0,-+$('null-pref').value,0,0],dq=dls(J,mv(J,v),.0001),n=sub(v,dq),leak=norm(mv(J,n));$('null-output').innerHTML=`<strong>投影後關節變化=${vec(n,3)}</strong><br>預測末端扭量洩漏=${leak.toExponential(2)}。理想偽逆下為零；數值阻尼與浮點誤差會留下小量。零空間動作可改肘姿，但仍須檢查關節極限與碰撞。`};on('null-pref','input',draw);draw()}
function singular(){if(!$('sing-elbow'))return;const draw=()=>{const q=[0,.2,0,rad(+$('sing-elbow').value),0,rad(+$('sing-wrist').value),0],J=jac(q),A=mm(J,tr(J)),w=Math.sqrt(Math.max(0,det(A))),dq=dls(J,[.05,0,0,0,0,0],+.08);$('sing-output').innerHTML=`<strong>可操作度代理值 √det(JJᵀ)=${w.toExponential(3)}</strong><br>要產生 x 方向 0.05 m/s 的阻尼解，關節速度範數=${fmt(norm(dq))} rad/s。值接近零表示至少一個任務方向變弱；對 6×7 的 J 應看秩或奇異值，不可寫 det(J)。`};['sing-elbow','sing-wrist'].forEach(x=>on(x,'input',draw));draw()}
let ikq=[0,.2,0,.7,0,-.4,0];
function orientErr(R,Rd){let e=[0,0,0];for(let i=0;i<3;i++)e=add(e,cross(R.map(r=>r[i]),Rd.map(r=>r[i])));return scale(e,.5)}
function ik(){if(!$('ik-run'))return;const target=()=>[+$('ik-x').value,+$('ik-y').value,+$('ik-z').value], step=()=>{const T=fk(ikq),eP=sub(target(),pos(T)),Rd=Rof(Rot('z',rad(+$('ik-yaw').value))),e=[...eP,...scale(orientErr(Rof(T),Rd),.6)],dq=dls(jac(ikq),e,+$('ik-lambda').value);ikq=ikq.map((q,i)=>clamp(q+clamp(dq[i],-.2,.2),-2.8,2.8));return norm(e)},draw=(msg='')=>{const T=fk(ikq),ep=norm(sub(target(),pos(T)));$('ik-output').innerHTML=`<strong>位置誤差=${fmt(ep,4)} m</strong><br>q（度）=${vec(ikq.map(deg),1)}<br>${msg}每步限制關節增量並夾在示意極限內；誤差不降可能是不可達、姿態衝突、局部極小或阻尼過大。`};on('ik-step','click',()=>{const e=step();draw(`一步後六維加權誤差=${fmt(e,4)}。`)});on('ik-run','click',()=>{let e;for(let i=0;i<40;i++){e=step();if(e<1e-3)break}draw(`批次迭代停止，六維加權誤差=${fmt(e,4)}。`)});on('ik-reset','click',()=>{ikq=[0,.2,0,.7,0,-.4,0];draw('已重設。')});draw()}
function contract(){if(!$('cpp-frame'))return;const draw=()=>{const ok=$('cpp-frame').value==='typed'&&$('cpp-unit').value==='rad'&&$('cpp-layout').value==='explicit';$('cpp-output').innerHTML=`<strong>${ok?'契約足以進入數值測試':'仍有語意型別風險'}</strong><br>${$('cpp-frame').value==='typed'?'來源／目標座標系進入型別。':'裸向量無法阻止基座點誤當工具點。'} ${$('cpp-unit').value==='rad'?'內部統一弧度。':'三角函數若收到度數會靜默產生錯誤。'} ${$('cpp-layout').value==='explicit'?'明確定義矩陣儲存與乘法語意。':'列主序／欄主序與數學左右乘可能被混淆。'}`};['cpp-frame','cpp-unit','cpp-layout'].forEach(x=>on(x,'input',draw));draw()}
function dictionary(){const q=$('term-search');if(!q)return;const cards=[...document.querySelectorAll('.term-card')],draw=()=>{const s=q.value.trim().toLocaleLowerCase('zh-Hant');let n=0;cards.forEach(c=>{const hit=c.textContent.toLocaleLowerCase('zh-Hant').includes(s);c.hidden=!hit;if(hit)n++});$('term-count').textContent=`顯示 ${n} 個條目`};on('term-search','input',draw);draw()}
[angleBasics,frame,planar,ik2,rotation,transform,seven,jacobian,nullspace,singular,ik,contract,dictionary].forEach(f=>f());
const navLabels={"02 2R":"02 二連桿","02 二連桿 FK／IK":"02 二連桿正逆運動學","05 FK":"05 正運動學","05 七軸 FK":"05 七軸正運動學","06 J":"06 雅可比","09 IK":"09 逆運動學"};document.querySelectorAll(".topbar a").forEach(a=>{if(navLabels[a.textContent])a.textContent=navLabels[a.textContent]});const firstEyebrow=document.querySelectorAll(".eyebrow")[0];if(firstEyebrow?.textContent.includes("SERIAL MANIPULATOR"))firstEyebrow.textContent="從零建立七旋轉關節串聯手臂模型";
if(typeof module!=="undefined")module.exports={fk,jac,dls,Rot,Rof,pos,mm,mv,tr,sub,norm};
