"use strict";
const $=x=>document.getElementById(x), on=(x,e,f)=>{const n=$(x);if(n)n.addEventListener(e,f)}, rad=d=>d*Math.PI/180, deg=r=>r*180/Math.PI, clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const I=n=>Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j?1:0));
const mm=(A,B)=>A.map(r=>B[0].map((_,j)=>r.reduce((s,v,k)=>s+v*B[k][j],0)));
const mv=(A,v)=>A.map(r=>r.reduce((s,x,i)=>s+x*v[i],0));
const tr=A=>A[0].map((_,j)=>A.map(r=>r[j]));
const add=(a,b)=>a.map((x,i)=>x+b[i]), sub=(a,b)=>a.map((x,i)=>x-b[i]), scale=(a,s)=>a.map(x=>x*s), dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0), norm=a=>Math.hypot(...a), cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const Tmul=(A,B)=>mm(A,B), Tx=x=>[[1,0,0,x],[0,1,0,0],[0,0,1,0],[0,0,0,1]], Tz=z=>[[1,0,0,0],[0,1,0,0],[0,0,1,z],[0,0,0,1]];
const Rot=(axis,a)=>{const c=Math.cos(a),s=Math.sin(a),R=axis==="x"?[[1,0,0],[0,c,-s],[0,s,c]]:axis==="y"?[[c,0,s],[0,1,0],[-s,0,c]]:[[c,-s,0],[s,c,0],[0,0,1]];return [[...R[0],0],[...R[1],0],[...R[2],0],[0,0,0,1]]};
const pos=T=>[T[0][3],T[1][3],T[2][3]], Rof=T=>T.slice(0,3).map(r=>r.slice(0,3)), fmt=(x,n=3)=>{const s=Number(x).toFixed(n);return Number(s)===0?(0).toFixed(n):s}, vec=(v,n=3)=>`[${v.map(x=>fmt(x,n)).join(", ")}]`;
const jointLimitsDeg=[170,120,170,140,170,120,175], jointLimits=jointLimitsDeg.map(rad);
const axes=["z","y","x","y","x","y","x"];
function fk(q,details=false){let T=Tz(.20), origins=[],worldAxes=[];for(let i=0;i<7;i++){const R=Rof(T),u=axes[i]==="x"?[1,0,0]:axes[i]==="y"?[0,1,0]:[0,0,1];origins.push(pos(T));worldAxes.push(mv(R,u));T=Tmul(T,Rot(axes[i],q[i]));if(i===2)T=Tmul(T,Tx(.32));if(i===3)T=Tmul(T,Tx(.28));if(i===5)T=Tmul(T,Tx(.12))}return details?{T,origins,worldAxes}:T}
function jac(q){const d=fk(q,true),p=pos(d.T),J=Array.from({length:6},()=>Array(7).fill(0));for(let i=0;i<7;i++){const v=cross(d.worldAxes[i],sub(p,d.origins[i]));for(let r=0;r<3;r++){J[r][i]=v[r];J[r+3][i]=d.worldAxes[i][r]}}return J}
function solve(A,b){A=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<A.length;i++){let p=i;for(let r=i+1;r<A.length;r++)if(Math.abs(A[r][i])>Math.abs(A[p][i]))p=r;[A[i],A[p]]=[A[p],A[i]];if(Math.abs(A[i][i])<1e-12)return null;const d=A[i][i];for(let j=i;j<=A.length;j++)A[i][j]/=d;for(let r=0;r<A.length;r++)if(r!==i){const f=A[r][i];for(let j=i;j<=A.length;j++)A[r][j]-=f*A[i][j]}}return A.map(r=>r[A.length])}
function dls(J,e,l=.08){const JT=tr(J),A=mm(J,JT);for(let i=0;i<6;i++)A[i][i]+=l*l;const y=solve(A,e);return y?mv(JT,y):Array(7).fill(0)}
function det(A){A=A.map(r=>[...r]);let d=1;for(let i=0;i<A.length;i++){let p=i;for(let r=i+1;r<A.length;r++)if(Math.abs(A[r][i])>Math.abs(A[p][i]))p=r;if(Math.abs(A[p][i])<1e-12)return 0;if(p!==i){[A[i],A[p]]=[A[p],A[i]];d*=-1}d*=A[i][i];for(let r=i+1;r<A.length;r++){const f=A[r][i]/A[i][i];for(let j=i;j<A.length;j++)A[r][j]-=f*A[i][j]}}return d}
function symmetricEigen(A){A=A.map(r=>[...r]);const V=I(A.length);for(let k=0;k<80;k++){let p=0,q=1,best=0;for(let i=0;i<A.length;i++)for(let j=i+1;j<A.length;j++)if(Math.abs(A[i][j])>best){best=Math.abs(A[i][j]);p=i;q=j}if(best<1e-14)break;const phi=.5*Math.atan2(2*A[p][q],A[q][q]-A[p][p]),c=Math.cos(phi),s=Math.sin(phi),app=c*c*A[p][p]-2*s*c*A[p][q]+s*s*A[q][q],aqq=s*s*A[p][p]+2*s*c*A[p][q]+c*c*A[q][q];for(let i=0;i<A.length;i++)if(i!==p&&i!==q){const aip=A[i][p],aiq=A[i][q];A[i][p]=A[p][i]=c*aip-s*aiq;A[i][q]=A[q][i]=s*aip+c*aiq}A[p][p]=app;A[q][q]=aqq;A[p][q]=A[q][p]=0;for(let i=0;i<V.length;i++){const vip=V[i][p],viq=V[i][q];V[i][p]=c*vip-s*viq;V[i][q]=s*vip+c*viq}}return {values:A.map((r,i)=>r[i]),vectors:V}}
function frame(){if(!$('frame-angle'))return;const draw=()=>{const a=rad(+$('frame-angle').value),x=+$('frame-x').value,y=+$('frame-y').value,c=Math.cos(a),s=Math.sin(a);$('frame-output').innerHTML=`<strong>同一自由向量在旋轉座標系中的分量：${vec([c*x+s*y,-s*x+c*y],2)}</strong><br>這是被動換座標：幾何箭頭沒有轉，只是基底轉了。若主動旋轉箭頭，矩陣符號方向相反。`};['frame-angle','frame-x','frame-y'].forEach(x=>on(x,'input',draw));draw()}
function angleBasics(){if(!$('angle-deg'))return;const draw=()=>{const d=+$('angle-deg').value,a=rad(d);$('angle-output').innerHTML=`<strong>${fmt(d,0)}° = ${fmt(a,4)} rad</strong><br>長度 1 的箭頭方向分量為 [cosθ, sinθ] = [${fmt(Math.cos(a),3)}, ${fmt(Math.sin(a),3)}]。更多位數：cosθ=${Math.cos(a).toExponential(3)}。平方和約 ${fmt(Math.cos(a)**2+Math.sin(a)**2,3)}，所以旋轉沒有改變箭頭長度。`};on('angle-deg','input',draw);draw()}
function planar(){if(!$('arm-q1'))return;const draw=()=>{const a=rad(+$('arm-q1').value),b=rad(+$('arm-q2').value),l1=.6,l2=.4,x=l1*Math.cos(a)+l2*Math.cos(a+b),y=l1*Math.sin(a)+l2*Math.sin(a+b);$('arm-output').innerHTML=`<strong>末端位置 = ${vec([x,y])} m</strong><br>第二段的絕對方向是 q₁+q₂，不是 q₂。距離基座 ${fmt(Math.hypot(x,y))} m；可達範圍為 0.2–1.0 m。`};['arm-q1','arm-q2'].forEach(x=>on(x,'input',draw));draw()}
function ik2(){if(!$('ik2-x'))return;const draw=()=>{const x=+$('ik2-x').value,y=+$('ik2-y').value,l1=.6,l2=.4,c=(x*x+y*y-l1*l1-l2*l2)/(2*l1*l2);if(Math.abs(c)>1+1e-12){$('ik2-output').innerHTML=`<strong>目標 ${vec([x,y],2)} m：不可達。</strong><br>目標距離超出兩連桿的環形工作空間；數值法再努力也不能改變幾何。`;return}const b=Math.acos(clamp(c,-1,1)),sol=[b,-b].map(q2=>[Math.atan2(y,x)-Math.atan2(l2*Math.sin(q2),l1+l2*Math.cos(q2)),q2]);if(Math.abs(Math.sin(b))<1e-10){$('ik2-output').innerHTML=`<strong>目標 ${vec([x,y],2)} m：邊界解。</strong><br>兩分支合併為一解（奇異）：q₁=${fmt(deg(sol[0][0]),1)}°，q₂=${fmt(deg(sol[0][1]),1)}°。`;return}$('ik2-output').innerHTML=`<strong>目標 ${vec([x,y],2)} m，兩組解：</strong><br>${sol.map(q=>`分支 q₂${q[1]>=0?'≥0':'&lt;0'}：q₁=${fmt(deg(q[0]),1)}°，q₂=${fmt(deg(q[1]),1)}°`).join('<br>')}<br>逆運動學不是函式反解的單一答案；若要稱肘上／肘下，必須另行明定相對「基座→目標」連線的側別。`};['ik2-x','ik2-y'].forEach(x=>on(x,'input',draw));draw()}
function rotation(){if(!$('rot-a'))return;const draw=()=>{const a=rad(+$('rot-a').value),b=rad(+$('rot-b').value),p=[1,0,0,1],R1=Tmul(Rot('y',b),Rot('z',a)),R2=Tmul(Rot('z',a),Rot('y',b));$('rot-output').innerHTML=`<strong>先 Z 後 Y：${vec(mv(R1,p).slice(0,3))}</strong><br>先 Y 後 Z：${vec(mv(R2,p).slice(0,3))}<br>此處採欄向量與固定世界軸，右側矩陣先作用；三維旋轉通常不可交換。`};['rot-a','rot-b'].forEach(x=>on(x,'input',draw));draw()}
function transform(){if(!$('tf-parent'))return;const draw=()=>{const a=rad(+$('tf-parent').value),b=rad(+$('tf-child').value),A=Tmul(Rot('z',a),Tx(.5)),B=Tmul(Rot('z',b),Tx(.3)),C=Tmul(A,B);$('tf-output').innerHTML=`<strong>末端原點（基座座標）=${vec(pos(C))}</strong><br><code>⁰T₂ = ⁰T₁ · ¹T₂</code>。右邊的局部變換先作用；交換乘法會描述另一條幾何鏈。`};['tf-parent','tf-child'].forEach(x=>on(x,'input',draw));draw()}
function qValues(){return Array.from({length:7},(_,i)=>rad(+($(`q${i+1}`)?.value||0)))}
function seven(){if(!$('q1'))return;for(let i=1;i<=7;i++){const el=$(`q${i}`),lim=jointLimitsDeg[i-1];el.min=-lim;el.max=lim}const draw=()=>{const q=qValues(),d=fk(q,true),T=d.T,R=Rof(T),rows=d.origins.map((o,i)=>`<tr><td>${i+1}</td><td>${vec(o)}</td><td>${vec(d.worldAxes[i])}</td></tr>`).join('');$('seven-output').innerHTML=`<strong>關節角（度）=${vec(q.map(deg),1)}</strong><br>本模型的正俯仰角會使後續連桿朝世界 −z 方向轉動。<br><strong>末端位置=${vec(pos(T))} m</strong><br>工具 x 軸=${vec(R.map(r=>r[0]))}<br>工具 z 軸=${vec(R.map(r=>r[2]))}<table><thead><tr><th>關節</th><th>原點（m）</th><th>世界軸向</th></tr></thead><tbody>${rows}</tbody></table>位置只是位姿的一半；兩組關節角可到同一點但工具方向不同。`};for(let i=1;i<=7;i++)on(`q${i}`,'input',draw);on('q-reset','click',()=>{for(let i=1;i<=7;i++)$(`q${i}`).value=0;draw()});draw()}
function jacobian(){if(!$('jac-joint'))return;const draw=()=>{const q=[0,.35,-.2,.7,.1,-.4,.2],J=jac(q),i=+$('jac-joint').value,lin=J.slice(0,3).map(r=>r[i]),ang=J.slice(3).map(r=>r[i]);$('jac-output').innerHTML=`<strong>測試 q（度）=${vec(q.map(deg),1)}；第 ${i+1} 欄</strong><br>末端線速度貢獻=${vec(lin)} m/s（當該關節為 1 rad/s）<br>角速度貢獻=${vec(ang)} rad/s<br>旋轉關節公式：線速度欄 = 軸向量 ×（末端位置 − 關節原點）。`};on('jac-joint','input',draw);draw()}
function nullspace(){if(!$('null-pref'))return;const draw=()=>{const q=[0,.35,-.2,.7,.1,-.4,.2],J=jac(q),v=[0,0,+$('null-pref').value,0,-+$('null-pref').value,0,0],dq=dls(J,mv(J,v),.0001),n=sub(v,dq),leak=norm(mv(J,n));$('null-output').innerHTML=`<strong>測試 q（度）=${vec(q.map(deg),1)}</strong><br><strong>投影後關節變化=${vec(n,3)}</strong><br>預測末端扭量洩漏=${leak.toExponential(2)}。理想偽逆下為零；數值阻尼與浮點誤差會留下小量。零空間動作可改肘姿，但仍須檢查關節極限與碰撞。`};on('null-pref','input',draw);draw()}
function singular(){if(!$('sing-elbow'))return;const draw=()=>{const q=[0,.2,0,rad(+$('sing-elbow').value),0,rad(+$('sing-wrist').value),0],J=jac(q),A=mm(J,tr(J)),w=Math.sqrt(Math.max(0,det(A))),V=[.05,0,0,0,0,0],dq=dls(J,V,.08),achieved=mv(J,dq),residual=sub(V,achieved),eig=symmetricEigen(A),sig=eig.values.map(x=>Math.sqrt(Math.max(0,x))),minIndex=sig.indexOf(Math.min(...sig)),smax=Math.max(...sig),rank=sig.filter(x=>x>smax*1e-6).length,weak=eig.vectors.map(r=>r[minIndex]);let pinvTask=Array(6).fill(0);for(let i=0;i<6;i++)if(sig[i]>smax*1e-10){const u=eig.vectors.map(r=>r[i]),gain=dot(u,V)/(sig[i]*sig[i]);pinvTask=add(pinvTask,scale(u,gain))}const pinv=mv(tr(J),pinvTask);$('sing-output').innerHTML=`<strong>輸入：肘 ${fmt(+$('sing-elbow').value,0)}°，腕 ${fmt(+$('sing-wrist').value,0)}°</strong><br>可操作度代理值 √det(JJᵀ)=${w.toExponential(3)}<br>最小奇異值 σ<sub>min</sub>=${Math.min(...sig).toExponential(3)}，數值秩=${rank}，弱末端方向=${vec(weak)}<br>未阻尼偽逆 ‖J⁺V‖=${fmt(norm(pinv))} rad/s；阻尼解 ‖Δq‖=${fmt(norm(dq))} rad/s<br>要求速度=${vec(V)}，實際達成=${vec(achieved)}，殘差=${fmt(norm(residual),4)}。<br>阻尼解在奇異附近變小，是因為它放棄達成弱方向速度，不是手臂變得更好動。正好失秩時，Moore–Penrose 偽逆也會捨棄零奇異值方向。`};['sing-elbow','sing-wrist'].forEach(x=>on(x,'input',draw));draw()}
let ikq=[0,-.2,0,-.7,0,.4,0];
function orientErr(R,Rd){let e=[0,0,0];for(let i=0;i<3;i++)e=add(e,cross(R.map(r=>r[i]),Rd.map(r=>r[i])));return scale(e,.5)}
function ik(){if(!$('ik-run'))return;const target=()=>[+$('ik-x').value,+$('ik-y').value,+$('ik-z').value],Rd=()=>Rof(Rot('z',rad(+$('ik-yaw').value))),metrics=(dqNorm=0,limited=false)=>{const T=fk(ikq),ep=norm(sub(target(),pos(T))),D=mm(tr(Rof(T)),Rd()),angle=Math.acos(clamp((D[0][0]+D[1][1]+D[2][2]-1)/2,-1,1)),weighted=norm([...sub(target(),pos(T)),...scale(orientErr(Rof(T),Rd()),.6)]);return {ep,angle,weighted,dqNorm,limited}},step=()=>{const T=fk(ikq),eP=sub(target(),pos(T)),e=[...eP,...scale(orientErr(Rof(T),Rd()),.6)],raw=dls(jac(ikq),e,+$('ik-lambda').value),max=Math.max(...raw.map(Math.abs)),s=max>.2?.2/max:1,dq=scale(raw,s);let limited=s<1;ikq=ikq.map((q,i)=>{const next=q+dq[i],clipped=clamp(next,-jointLimits[i],jointLimits[i]);if(clipped!==next)limited=true;return clipped});return metrics(norm(dq),limited)},draw=(m=metrics(),reason='未執行')=>{$('ik-output').innerHTML=`<strong>輸入：目標=${vec(target(),2)} m，yaw=${fmt(+$('ik-yaw').value,0)}°，λ=${fmt(+$('ik-lambda').value,2)}</strong><br>位置誤差=${fmt(m.ep,4)} m；姿態夾角誤差=${fmt(deg(m.angle),2)}°<br>本步 ‖Δq‖=${fmt(m.dqNorm,4)} rad；觸發縮放／極限=${m.limited?'是':'否'}<br>q（度）=${vec(ikq.map(deg),1)}<br>停止原因=${reason}；六維加權誤差=${fmt(m.weighted,4)}。<br>每步會整體等比縮小過大的關節增量，再夾在各軸示意極限內。`};on('ik-step','click',()=>{const m=step();draw(m,'single_step')});on('ik-run','click',()=>{let m=metrics(),reason='max_iterations',steps=0;for(;steps<40;steps++){m=step();if(!Number.isFinite(m.weighted)){reason='invalid_number';break}if(m.ep<.001&&m.angle<rad(.5)){reason='converged';steps++;break}if(m.dqNorm<1e-6){reason='stalled';steps++;break}}draw(m,`${reason}（${steps} 步）`)});on('ik-reset','click',()=>{ikq=[0,-.2,0,-.7,0,.4,0];draw(metrics(),'已重設')});draw()}
function contract(){if(!$('cpp-frame'))return;const draw=()=>{const ok=$('cpp-frame').value==='typed'&&$('cpp-unit').value==='rad'&&$('cpp-layout').value==='explicit';$('cpp-output').innerHTML=`<strong>${ok?'契約足以進入數值測試':'仍有語意型別風險'}</strong><br>${$('cpp-frame').value==='typed'?'來源／目標座標系進入型別。':'裸向量無法阻止基座點誤當工具點。'} ${$('cpp-unit').value==='rad'?'內部統一弧度。':'三角函數若收到度數會靜默產生錯誤。'} ${$('cpp-layout').value==='explicit'?'明確定義矩陣儲存與乘法語意。':'列主序／欄主序與數學左右乘可能被混淆。'}`};['cpp-frame','cpp-unit','cpp-layout'].forEach(x=>on(x,'input',draw));draw()}
function lieGroup(){if(!$('lie-v'))return;const draw=()=>{const v=+$('lie-v').value,w=rad(+$('lie-w').value),t=+$('lie-dt').value,theta=w*t;let x,y,r;if(Math.abs(w)<1e-9){x=v*t;y=0;r=Infinity}else{r=v/w;x=r*Math.sin(theta);y=r*(1-Math.cos(theta))}const path=Math.abs(v*t),kind=Math.abs(w)<1e-9?'直線':'圓弧';$('lie-output').innerHTML=`<strong>${kind}積分後位姿：x=${fmt(x,3)} m，y=${fmt(y,3)} m，θ=${fmt(deg(theta),1)}°。</strong><br>路程 ${fmt(path,3)} m；${Number.isFinite(r)?`帶符號轉彎半徑 v/ω=${fmt(r,3)} m。`:'ω=0，因此半徑趨近無限大。'} 這是固定 body twist 的平面精確積分，不是把平移與旋轉任意相加。`};['lie-v','lie-w','lie-dt'].forEach(x=>on(x,'input',draw));draw()}
function lieFrames(){if(!$('lie-frame-angle'))return;const draw=()=>{const a=rad(+$('lie-frame-angle').value),d=+$('lie-frame-distance').value,body=[d*Math.cos(a),d*Math.sin(a)],space=[d,0];$('lie-frame-output').innerHTML=`<strong>工具已轉 ${fmt(+$('lie-frame-angle').value,0)}°，再前進 ${fmt(d,2)} m</strong><br>body 右乘（沿工具 x）終點=${vec(body)} m<br>space 左乘（沿世界 x）終點=${vec(space)} m<br>同一個「向前」數值若缺少 frame 標籤，會得到不同物理運動。`};['lie-frame-angle','lie-frame-distance'].forEach(x=>on(x,'input',draw));draw()}
function kinematicCalibration(){if(!$('kcal-link'))return;const draw=()=>{const l=.6,dl=+$('kcal-link').value/1000,dq=rad(+$('kcal-zero').value),q=rad(45),N=+$('kcal-samples').value,nom=[l*Math.cos(q),l*Math.sin(q)],actual=[(l+dl)*Math.cos(q+dq),(l+dl)*Math.sin(q+dq)],bias=norm(sub(actual,nom)),random=.001/Math.sqrt(N);$('kcal-output').innerHTML=`<strong>末端系統偏差約 ${fmt(bias*1000,2)} mm；平均值隨機標準不確定度約 ${fmt(random*1000,3)} mm。</strong><br>互動假設單次量測隨機標準差 1 mm、彼此獨立。增加到 N=${N} 只讓隨機部分按 1/√N 下降，不會消除連桿長度與零點造成的 ${fmt(bias*1000,2)} mm 偏差。`};['kcal-link','kcal-zero','kcal-samples'].forEach(x=>on(x,'input',draw));draw()}
function dictionary(){const q=$('term-search');if(!q)return;const cards=[...document.querySelectorAll('.term-card')],draw=()=>{const s=q.value.trim().toLocaleLowerCase('zh-Hant');let n=0;cards.forEach(c=>{const hit=c.textContent.toLocaleLowerCase('zh-Hant').includes(s);c.hidden=!hit;if(hit)n++});$('term-count').textContent=`顯示 ${n} 個條目`};on('term-search','input',draw);draw()}
[angleBasics,frame,planar,ik2,rotation,transform,seven,jacobian,nullspace,singular,ik,contract,lieGroup,lieFrames,kinematicCalibration,dictionary].forEach(f=>f());
document.querySelectorAll('input[type="range"]').forEach(input=>{let output=input.nextElementSibling;if(!output||output.tagName!=='OUTPUT'){output=document.createElement('output');input.insertAdjacentElement('afterend',output)}output.htmlFor=input.id;const draw=()=>{output.value=input.value;output.textContent=` ${input.value}`};input.addEventListener('input',draw);draw()});
if(typeof module!=="undefined")module.exports={fk,jac,dls,Rot,Rof,pos,mm,mv,tr,sub,norm};
