"use strict";
const $=id=>document.getElementById(id),on=(id,e,f)=>{const n=$(id);if(n)n.addEventListener(e,f)},num=id=>Number($(id)?.value),fmt=(x,d=2)=>Number(x).toFixed(d);
function projection(){if(!$("proj-x"))return;const draw=()=>{const X=num("proj-x"),Y=num("proj-y"),Z=num("proj-z"),fx=num("proj-fx"),cx=320,cy=240;if(Z<=0){$("proj-output").innerHTML="<strong>點不在相機前方。</strong><br>針孔模型要求相機座標 Z&gt;0。";return}const u=fx*X/Z+cx,v=fx*Y/Z+cy;$("proj-output").innerHTML=`<strong>像素約為 (u,v)=(${fmt(u,1)}, ${fmt(v,1)})。</strong><br>同一 X、Y 在 Z 增大時靠近主點；單一像素沒有保留絕對深度。`};["proj-x","proj-y","proj-z","proj-fx"].forEach(x=>on(x,"input",draw));draw()}
function calibration(){if(!$("cal-fx-error"))return;const draw=()=>{const e=num("cal-fx-error"),radius=num("cal-radius"),pixel=Math.abs(e)*radius/100;const status=pixel<1?"小但不可忽略":pixel<5?"足以影響精密抓取":"模型或資料明顯不合";$("cal-output").innerHTML=`<strong>示意投影偏差 ${fmt(pixel,2)} px：${status}。</strong><br>這只是焦距比例誤差的線性近似；真實殘差還包含畸變、角點定位、姿態覆蓋與標定板誤差。`};["cal-fx-error","cal-radius"].forEach(x=>on(x,"input",draw));draw()}
function ransac(){if(!$("ransac-inlier"))return;const draw=()=>{const w=num("ransac-inlier"),s=num("ransac-sample"),N=num("ransac-iter"),p=1-Math.pow(1-Math.pow(w,s),N);$("ransac-output").innerHTML=`<strong>至少一次抽到全內點最小集的理想機率：${fmt(100*p,1)}%</strong><br>P=1−(1−w<sup>s</sup>)<sup>N</sup>。它不保證模型正確：內點閾值、退化幾何與錯誤匹配結構仍會造成假解。`};["ransac-inlier","ransac-sample","ransac-iter"].forEach(x=>on(x,"input",draw));draw()}
function stereo(){if(!$("stereo-f"))return;const draw=()=>{const f=num("stereo-f"),b=num("stereo-b"),d=num("stereo-d"),Z=f*b/d,dz=f*b/(d*d);$("stereo-output").innerHTML=`<strong>深度 Z≈${fmt(Z,3)} m。</strong><br>若視差誤差約 1 px，局部深度誤差量級約 ${fmt(dz,3)} m。距離越遠、視差越小，深度越敏感。`};["stereo-f","stereo-b","stereo-d"].forEach(x=>on(x,"input",draw));draw()}
function latency(){if(!$("lat-speed"))return;const draw=()=>{const v=num("lat-speed"),ms=num("lat-ms"),dx=v*ms/1000;$("lat-output").innerHTML=`<strong>在資料到達控制器前，目標可移動 ${fmt(dx*1000,1)} mm。</strong><br>延遲包含曝光、傳輸、排隊、推論、控制與致動；平均延遲不足以描述抖動與最壞情況。`};["lat-speed","lat-ms"].forEach(x=>on(x,"input",draw));draw()}
function evidence(){if(!$("ev-time"))return;const draw=()=>{const t=$("ev-time").value==="yes",frame=$("ev-frame").value==="yes",unc=$("ev-unc").value==="yes";let s=t&&frame&&unc?"證據足以進入融合與控制驗證":"感知輸出仍缺語意契約";let why=!t?"缺時間戳，無法對齊機器人狀態。":!frame?"缺座標系，位姿數值沒有幾何意義。":!unc?"缺品質／不確定度，控制器無法判斷何時拒用。":"仍須以真值、失敗案例與延遲分布驗證。";$("ev-output").innerHTML=`<strong>${s}</strong><br>${why}`};["ev-time","ev-frame","ev-unc"].forEach(x=>on(x,"input",draw));draw()}
function fusion(){if(!$("fusion-prior"))return;const draw=()=>{const prior=num("fusion-prior"),priorSd=num("fusion-prior-sd"),measure=num("fusion-measure"),measureSd=num("fusion-measure-sd"),P=priorSd*priorSd,R=measureSd*measureSd,K=P/(P+R),post=prior+K*(measure-prior),postSd=Math.sqrt((1-K)*P),innovation=measure-prior;$("fusion-output").innerHTML=`<strong>後驗位置 ${fmt(post,3)} m，標準差 ${fmt(postSd,3)} m，Kalman 增益 K=${fmt(K,3)}。</strong><br>創新 z−μ⁻=${fmt(innovation,3)} m；量測越精確，K 越接近 1。公式假設兩者量測同一狀態、時間與座標，且誤差獨立、無偏、近似高斯。`};["fusion-prior","fusion-prior-sd","fusion-measure","fusion-measure-sd"].forEach(x=>on(x,"input",draw));draw()}
function slam(){if(!$("slam-distance"))return;const draw=()=>{const distance=num("slam-distance"),bias=num("slam-bias")/100,noise=num("slam-step-noise")/1000,loop=num("slam-loop")/100,systematic=distance*bias,random=noise*Math.sqrt(distance),before=Math.hypot(systematic,random),after=before*(1-loop);$("slam-output").innerHTML=`<strong>閉環前漂移尺度約 ${fmt(before,3)} m；校正後示意剩 ${fmt(after,3)} m。</strong><br>其中系統項 ${fmt(systematic,3)} m、隨機項 ${fmt(random,3)} m。閉環校正 ${fmt(loop*100,0)}% 只是教學旋鈕；真實圖最佳化依約束、協方差、拓樸與外點決定，不能保證回到真值。`};["slam-distance","slam-bias","slam-step-noise","slam-loop"].forEach(x=>on(x,"input",draw));draw()}
function dictionary(){const q=$("term-search");if(!q)return;const cards=[...document.querySelectorAll(".term-card")],draw=()=>{const s=q.value.trim().toLocaleLowerCase("zh-Hant");let c=0;cards.forEach(x=>{const hit=x.textContent.toLocaleLowerCase("zh-Hant").includes(s);x.hidden=!hit;if(hit)c++});$("term-count").textContent=`顯示 ${c} 個條目`};on("term-search","input",draw);draw()}
[projection,calibration,ransac,stereo,latency,evidence,fusion,slam,dictionary].forEach(f=>f());
