"use strict";
const id=x=>document.getElementById(x);const on=(x,e,f)=>{const n=id(x);if(n)n.addEventListener(e,f)};const num=x=>Number(id(x)?.value||0);

function scopeTool(){if(!id("sample-source"))return;const draw=()=>{const source=id("sample-source").value,purpose=id("analysis-purpose").value,isolated=id("isolated").checked;let title,why;if(source==="owned"||source==="training"){title="範圍可進入分析規劃";why="先保存原始檔雜湊與授權紀錄，再在受控副本上觀察。"}else if(source==="authorized"){title="先核對書面授權邊界";why="確認可分析的版本、系統、時間、資料處理與可否動態執行。"}else{title="停止分析";why="來源與權利不明時，不應靠技術可行性取代授權。"}if(purpose==="bypass")why+=" 目前目的涉及繞過授權或控制，不在本課允許範圍。";if(!isolated)why+=" 動態分析前仍缺隔離與可回復環境。";id("scope-output").innerHTML=`<strong>${title}</strong><br>${why}`};["sample-source","analysis-purpose","isolated"].forEach(x=>on(x,"input",draw));draw()}

function machineTool(){if(!id("machine-next"))return;const program=["MOV R0, 3","MOV R1, 4","ADD R0, R1","CMP R0, 7","JZ 6","MOV R0, 0"];let pc=0,r0=0,r1=0,z=false;const draw=()=>{id("machine-output").innerHTML=`<strong>下一條位址：${pc}</strong><pre>R0=${r0}  R1=${r1}  零旗標=${z?1:0}\n${program.map((x,i)=>(i===pc?"> ":"  ")+i+": "+x).join("\n")}</pre>${pc>=program.length?"程式已離開示意指令序列。":"每一步只改變明確的機器狀態；助記符是位元組指令的可讀表示。"}`};on("machine-next","click",()=>{if(pc===0)r0=3;else if(pc===1)r1=4;else if(pc===2)r0+=r1;else if(pc===3)z=r0===7;else if(pc===4&&z){pc=6;draw();return}else if(pc===5)r0=0;pc++;draw()});on("machine-reset","click",()=>{pc=0;r0=0;r1=0;z=false;draw()});draw()}

function stackTool(){if(!id("stack-args"))return;const draw=()=>{const args=num("stack-args"),locals=num("stack-locals"),depth=num("stack-depth");const frame=16+Math.max(0,args-4)*8+locals;const aligned=Math.ceil(frame/16)*16;id("stack-output").innerHTML=`<strong>單一示意框架 ${aligned} 位元組；${depth} 層約 ${aligned*depth} 位元組。</strong><br>模型含 16 位元組保存資訊、前四個整數參數假設走暫存器、其餘每個 8 位元組，再加入 ${locals} 位元組區域資料並對齊到 16。真實規則由平台的應用程式二進位介面決定；最佳化可能省略框架或把值留在暫存器。`};["stack-args","stack-locals","stack-depth"].forEach(x=>on(x,"input",draw));draw()}

function loaderTool(){if(!id("load-base"))return;const draw=()=>{const base=num("load-base"),offset=num("load-offset");id("loader-output").innerHTML=`<strong>映射後虛擬位址：0x${(base+offset).toString(16).toUpperCase()}</strong><br>載入基底 0x${base.toString(16).toUpperCase()} + 區段內相對位移 0x${offset.toString(16).toUpperCase()}。若程式內有依賴實際位置的參照，載入器需依重定位資訊修正；可位置獨立的程式碼可減少此需求。`};["load-base","load-offset"].forEach(x=>on(x,"input",draw));draw()}

function staticTool(){if(!id("ev-string"))return;const draw=()=>{const items=[];if(id("ev-string").checked)items.push("可疑字串只是被包含或被引用的線索");if(id("ev-import").checked)items.push("匯入函式縮小可能能力，但不證明實際呼叫");if(id("ev-xref").checked)items.push("交叉參照把資料連到使用位置");if(id("ev-flow").checked)items.push("控制流展示可達路徑與條件");const strong=id("ev-xref").checked&&id("ev-flow").checked;id("static-output").innerHTML=`<strong>${items.length?strong?"已有可驗證的行為假說":"線索尚不足以支持行為結論":"尚未選取證據"}</strong><br>${items.join("；")||"先從檔案識別、雜湊、區段與可見字串建立盤點。"}${strong?"。下一步用受控動態觀察驗證該路徑是否執行。":"。保留替代解釋，不把存在性誤寫成執行事實。"}`};["ev-string","ev-import","ev-xref","ev-flow"].forEach(x=>on(x,"input",draw));draw()}

function debugTool(){if(!id("debug-pc"))return;const draw=()=>{const pc=num("debug-pc"),bp=id("debug-break").checked;const states=["尚未呼叫解析函式；輸入緩衝區存在","已進入解析函式；參數指向輸入","長度檢查完成；條件旗標已更新","依條件分支到接受或拒絕路徑","函式回傳；呼叫端取得結果"];id("debug-output").innerHTML=`<strong>${bp&&pc===2?"在長度檢查後暫停":"觀察位置在步驟 "+pc}</strong><br>${states[pc]}。${bp&&pc===2?"此時比較暫停前後的暫存器、記憶體與旗標，可驗證分支依賴哪個值。":"移動位置只改變教學時間線；真實除錯器需由中斷點、單步或事件使行程暫停。"}`};["debug-pc","debug-break"].forEach(x=>on(x,"input",draw));draw()}

function flowTool(){if(!id("flow-source"))return;const draw=()=>{const src=id("flow-source").value,branch=id("flow-branch").value;const sourceText={argument:"函式參數",file:"檔案讀入位元組",constant:"內嵌常數"}[src];const end=branch==="zero"?"拒絕路徑":"處理路徑";id("flow-output").innerHTML=`<strong>向前切片：${sourceText} → 長度正規化 → 比較 → ${end}</strong><br>控制流說明「可能走哪裡」；資料流說明「這個值從哪裡來、影響哪裡」。若看見大量無意義分支，先追真正影響輸出的定義使用鏈；不能因圖很複雜就斷定是惡意或混淆。`};["flow-source","flow-branch"].forEach(x=>on(x,"input",draw));draw()}

function malwareTool(){if(!id("malware-signal"))return;const draw=()=>{const v=id("malware-signal").value;const data={hash:["先保存原始樣本並計算密碼雜湊","用於樣本同一性與跨系統比對；單一雜湊命中不解釋行為"],process:["建立父子行程、命令列與時間線","交叉比對端點事件與合法軟體基線，不從程序名稱定罪"],network:["保存目的位址、名稱、連線時間與流量方向","網路指標可能是共享服務；需與行程及時間證據串接"],file:["比較建立、修改、刪除與執行事件","保留路徑、雜湊、簽章與產生它的行程；不要在生產端直接打開"]};const [first,why]=data[v];id("malware-output").innerHTML=`<strong>第一份證據：${first}</strong><br>${why}。分析副本留在隔離環境；原始證據維持唯讀與可追溯保管。若事件正在發生，依組織程序隔離、通報與保存，不自行反擊。`};on("malware-signal","input",draw);draw()}

function dictionary(){const q=id("term-search");if(!q)return;q.placeholder="例如：二進位介面、位址、暫停、證據";const draw=()=>{const s=q.value.trim().toLowerCase();let n=0;document.querySelectorAll(".term-card").forEach(c=>{const hit=!s||c.dataset.search.toLowerCase().includes(s);c.hidden=!hit;if(hit)n++});id("term-count").textContent=`顯示 ${n} 個條目`};q.addEventListener("input",draw);draw()}
const loaderPrereq=id("load-base")?document.querySelector(".prereq a"):null;if(loaderPrereq)loaderPrereq.textContent="編譯後模組需共同遵守應用程式二進位介面（Application Binary Interface, ABI）";
const machineIntro=id("machine-next")?document.querySelector(".workspace p"):null;if(machineIntro)machineIntro.innerHTML="這是虛構教學指令集；搬移（move, <code>MOV</code>）表示搬值、加法（add, <code>ADD</code>）做加法、比較（compare, <code>CMP</code>）設定旗標、零時跳躍（jump if zero, <code>JZ</code>）在零旗標成立時跳躍。大寫字樣是組合語言助記符。";
[scopeTool,machineTool,stackTool,loaderTool,staticTool,debugTool,flowTool,malwareTool,dictionary].forEach(f=>f());
